bazar: /home/julian/devel/artvertiser/garfeild/viewsets/affine_image_generator.cpp File Reference
affine_image_generator.cpp File Reference
#include <stdlib.h>
#include <math.h>
#include <iostream>
#include <starter.h>
#include "affine_image_generator.h"
Functions
static int min4 (int a, int b, int c, int d)
static int max4 (int a, int b, int c, int d)
static float min4 (float a, float b, float c, float d)
static float max4 (float a, float b, float c, float d)
Variables
static const int prime = 307189
Function Documentation
static float max4 (float a, float b, float c, float d) [static]
Definition at line 269 of file affine_image_generator.cpp.
static int max4 (int a, int b, int c, int d) [static]
Definition at line 259 of file affine_image_generator.cpp.
Referenced by affine_image_generator::generate_random_affine_transformation(), and affine_image_generator::inside_roi().
static float min4 (float a, float b, float c, float d) [static]
Definition at line 264 of file affine_image_generator.cpp.
static int min4 (int a, int b, int c, int d) [static]
Definition at line 254 of file affine_image_generator.cpp.
Referenced by affine_image_generator::generate_random_affine_transformation(), and affine_image_generator::inside_roi().
Variable Documentation
const int prime = 307189 [static]
Definition at line 31 of file affine_image_generator.cpp.
Referenced by affine_image_generator::add_white_noise(), affine_image_generator::affine_image_generator(), affine_image_generator::replace_by_noise(), and affine_image_generator::set_noise_level().