bazar: /home/julian/devel/artvertiser/samples/artvertiser/multicam.cpp File Reference
multicam.cpp File Reference
#include <iostream>
#include <vector>
#include <cv.h>
#include <highgui.h>
#include "multigrab.h"
Functions
void show_result (planar_object_recognizer &recognizer, IplImage *video, IplImage *dst)
static void augment_scene (int cam, CalibModel &model, IplImage *frame, IplImage *display)
bool geometric_calibration (MultiGrab &multi, bool cache)
bool photometric_calibration (MultiGrab &multi, int nbImages, bool cache)
void usage (const char *s)
int main (int argc, char **argv)
Function Documentation
static void augment_scene (int cam, CalibModel & model, IplImage * frame, IplImage * display) [static]
Examples:
fullcalib.cpp, and multicam.cpp.
Definition at line 301 of file multicam.cpp.
References CalibModel::augm, CalibModel::corners, LightMap::getBias(), LightMap::getGain(), CamAugmentation::GetObjectToWorld(), CamAugmentation::GetProjectionMatrix(), CalibModel::image, LightMap::isReady(), CalibModel::map, projPts, and LightMap::readMap().
Referenced by photometric_calibration().
bool geometric_calibration (MultiGrab & multi, bool cache)
Examples:
fullcalib.cpp, and multicam.cpp.
Definition at line 81 of file multicam.cpp.
References add_detected_homography(), CamCalibration::AddCamera(), CamCalibration::AddHomography(), CalibModel::augm, calib, CamCalibration::Calibrate(), MultiGrab::cams, MultiGrab::grabFrames(), CamAugmentation::LoadOptimalStructureFromFile(), MultiGrab::model, CamCalibration::PrintOptimizedResultsToFile1(), and show_result().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 30 of file multicam.cpp.
References MultiGrab::allocLightCollector(), geometric_calibration(), MultiGrab::init(), modelFile, multi, photometric_calibration(), and usage().
bool photometric_calibration (MultiGrab & multi, int nbImages, bool cache)
Examples:
fullcalib.cpp, and multicam.cpp.
Definition at line 181 of file multicam.cpp.
References CamAugmentation::Accomodate(), add_detected_homography(), CamAugmentation::AddHomography(), LightMap::addNormal(), CalibModel::augm, augment_scene(), MultiGrab::cams, CamAugmentation::Clear(), LightMap::computeLightParams(), frameOK, CamAugmentation::GetObjectToWorld(), MultiGrab::grabFrames(), LightMap::isReady(), LightMap::load(), CamAugmentation::LoadOptimalStructureFromFile(), CalibModel::map, MultiGrab::model, nbLightMeasures, and LightMap::save().
Referenced by main().
void show_result (planar_object_recognizer & recognizer, IplImage * video, IplImage * dst)
Definition at line 281 of file multicam.cpp.
References PyrImage::convCoordf(), cvPoint(), image_object_point_match::image_point, image_object_point_match::inlier, planar_object_recognizer::match_number, planar_object_recognizer::matches, planar_object_recognizer::object_is_detected, keypoint::scale, keypoint::u, and keypoint::v.
void usage (const char * s)
Definition at line 19 of file multicam.cpp.