bazar: /home/julian/devel/artvertiser/samples/artvertiser/artvertiser.cpp File Reference
artvertiser.cpp File Reference
#include <iostream>
#include <sstream>
#include <vector>
#include <cv.h>
#include <highgui.h>
#include <map>
#include <stdio.h>
#include <time.h>
#include <calib/camera.h>
#include "multigrab.h"
#include <GL/glut.h>
#include "/usr/include/freetype2/freetype/config/ftconfig.h"
#include <FTGL/ftgl.h>
Classes
struct artvert_struct
Defines
#define IsRGB(s) ((s[0] == 'R') && (s[1] == 'G') && (s[2] == 'B'))
#define IsBGR(s) ((s[0] == 'B') && (s[1] == 'G') && (s[2] == 'R'))
#define GL_CLAMP_TO_BORDER 0x812D
#define GL_MIRROR_CLAMP_EXT 0x8742
#define WIDTH 800
#define HEIGHT 450
#define NUMARTVERTS 5
Typedefs
typedef std::vector
< artvert_struct > artverts_list
typedef std::vector< IplImage > imgVec
Functions
artverts_list artverts (5)
static void photo_start ()
Starts photometric calibration.
static void geom_calib_start (bool cache)
Start geometric calibration. If the calibration can be loaded from disk, continue directly with photometric calibration.
void entry (int state)
void mouse (int button, int state, int x, int y)
static void drawText (IplImage *img, const char *text, CvPoint point, CvFont *font, CvScalar colour, double size)
static std::vector< int > readROI (const char *filename)
static void reshape (int width, int height)
GLUT callback on window size change.
static void usage (const char *s)
Print a command line help and exit.
static bool init (int argc, char **argv)
Initialize everything.
static void keyboard (unsigned char c, int x, int y)
static void emptyWindow ()
int main (int argc, char *argv[])
static bool drawBackground (IplTexture *tex)
Draw a frame contained in an IplTexture object on an OpenGL viewport.
static void geom_calib_draw (void)
A draw callback during camera calibration.
static void geom_calib_end ()
Called when geometric calibration ends. It makes sure that the CamAugmentation object is ready to work.
static void geom_calib_idle (void)
static void photo_draw (void)
static void photo_idle ()
Variables
MultiGrab * multi = 0
CamCalibration * calib = 0
CvPoint projPts [4]
IplTexture * frameTexture = 0
IplTexture * tex = 0
IplImage * image = 0
CvCapture * capture = 0
CvCapture * avi_capture = 0
IplImage * avi_image = 0
IplImage * avi_frame = 0
IplImage * image1 = cvLoadImage("artvert1.png")
IplImage * image2 = cvLoadImage("artvert2.png")
IplImage * image3 = cvLoadImage("artvert3.png")
IplImage * image4 = cvLoadImage("artvert4.png")
IplImage * image5 = cvLoadImage("artvert5.png")
bool frameOK = false
bool cacheLight = false
bool dynamicLight = false
bool sphereObject = false
bool avi_play = false
bool avi_play_init = false
bool lbuttonDown = false
bool label = false
int nbLightMeasures = 0
int geom_calib_nb_homography
int current_cam = 0
int avi_init = 0
int foundMatch = 0
int augment = 0
int cnt = 0
std::vector< int > roiVec
char * image_path
CvFont font
CvFont fontbold
GLenum format
GLuint imageID
static FTFont * ftglFont
float fade = 0.0
float fadeSpeed = 2.0
Define Documentation
#define GL_CLAMP_TO_BORDER 0x812D
Definition at line 141 of file artvertiser.cpp.
#define GL_MIRROR_CLAMP_EXT 0x8742
Definition at line 143 of file artvertiser.cpp.
#define HEIGHT 450
Definition at line 146 of file artvertiser.cpp.
Referenced by main(), photo_draw(), and reshape().
#define IsBGR (s) ((s[0] == 'B') && (s[1] == 'G') && (s[2] == 'R'))
Definition at line 138 of file artvertiser.cpp.
Referenced by photo_draw().
#define IsRGB (s) ((s[0] == 'R') && (s[1] == 'G') && (s[2] == 'B'))
Definition at line 137 of file artvertiser.cpp.
#define NUMARTVERTS 5
Definition at line 147 of file artvertiser.cpp.
Referenced by keyboard(), and mouse().
#define WIDTH 800
Definition at line 145 of file artvertiser.cpp.
Referenced by main(), photo_draw(), and reshape().
Typedef Documentation
typedef std::vector<artvert_struct> artverts_list
Definition at line 102 of file artvertiser.cpp.
typedef std::vector<IplImage> imgVec
Definition at line 106 of file artvertiser.cpp.
Function Documentation
artverts_list artverts (5)
Referenced by init(), and photo_draw().
static bool drawBackground (IplTexture * tex) [static]
Draw a frame contained in an IplTexture object on an OpenGL viewport.
Examples:
multigl.cpp.
Definition at line 428 of file artvertiser.cpp.
References IplTexture::disableTexture(), IplTexture::getIm(), IplTexture::loadTexture(), IplTexture::u(), and IplTexture::v().
Referenced by geom_calib_draw(), and photo_draw().
static void drawText (IplImage * img, const char * text, CvPoint point, CvFont * font, CvScalar colour, double size) [static]
Definition at line 218 of file artvertiser.cpp.
static void emptyWindow () [static]
Examples:
multigl.cpp.
Definition at line 395 of file artvertiser.cpp.
Referenced by main().
void entry (int state)
Definition at line 175 of file artvertiser.cpp.
Referenced by main().
static void geom_calib_draw (void) [static]
A draw callback during camera calibration.
GLUT calls that function during camera calibration when repainting the window is required. During geometric calibration, no 3D is known: we just plot 2d points where some feature points have been recognized.
Examples:
multigl.cpp.
Definition at line 471 of file artvertiser.cpp.
References MultiGrab::cams, PyrImage::convCoordf(), current_cam, drawBackground(), image_object_point_match::image_point, image_object_point_match::inlier, planar_object_recognizer::match_number, planar_object_recognizer::matches, planar_object_recognizer::object_is_detected, keypoint::scale, keypoint::u, and keypoint::v.
Referenced by geom_calib_start().
static void geom_calib_end () [static]
Called when geometric calibration ends. It makes sure that the CamAugmentation object is ready to work.
Examples:
multigl.cpp.
Definition at line 520 of file artvertiser.cpp.
References CalibModel::augm, CamAugmentation::LoadOptimalStructureFromFile(), and MultiGrab::model.
Referenced by geom_calib_idle().
static void geom_calib_idle (void) [static]
Called by GLUT during geometric calibration when there's nothing else to do. This function grab frames from camera(s), run the 2D detection on every image, and keep the result in memory for calibration. When enough homographies have been detected, it tries to actually calibrate the cameras.
Examples:
multigl.cpp.
Definition at line 539 of file artvertiser.cpp.
References add_detected_homography(), CamCalibration::AddHomography(), CamCalibration::Calibrate(), MultiGrab::cams, current_cam, geom_calib_end(), geom_calib_nb_homography, MultiGrab::grabFrames(), photo_start(), CamCalibration::PrintOptimizedResultsToFile1(), and IplTexture::setImage().
Referenced by geom_calib_start().
static void geom_calib_start (bool cache) [static]
Start geometric calibration. If the calibration can be loaded from disk, continue directly with photometric calibration.
Examples:
multigl.cpp.
Definition at line 594 of file artvertiser.cpp.
References CamCalibration::AddCamera(), CalibModel::augm, MultiGrab::cams, geom_calib_draw(), geom_calib_idle(), geom_calib_nb_homography, CamAugmentation::LoadOptimalStructureFromFile(), MultiGrab::model, and photo_start().
Referenced by init().
static bool init (int argc, char ** argv) [static]
Initialize everything.
Parse the command line
Initialize all the cameras
Load or interactively build a model, with its classifier.
Set the GLUT callbacks for geometric calibration or, if already done, for photometric calibration.
Examples:
multigl.cpp.
Definition at line 295 of file artvertiser.cpp.
References artverts(), avi_capture, avi_play, cacheLight, geom_calib_start(), image1, image2, image3, image4, image5, image_path, MultiGrab::init(), modelFile, readROI(), roiVec, and usage().
Referenced by main().
static void keyboard (unsigned char c, int x, int y) [static]
The keyboard callback: reacts to '+' and '-' to change the viewed cam, 'q' exits. 'd' turns on/off the dynamic lightmap update. 'f' goes fullscreen.
Examples:
multigl.cpp.
Definition at line 365 of file artvertiser.cpp.
References augment, avi_play, cnt, current_cam, dynamicLight, and NUMARTVERTS.
Referenced by main().
int main (int argc, char * argv[])
Examples:
augment3d.cpp, filedetect.cpp, fullcalib.cpp, multicam.cpp, multigl.cpp, and singlecalib.cpp.
Definition at line 400 of file artvertiser.cpp.
References emptyWindow(), entry(), ftglFont, HEIGHT, init(), keyboard(), mouse(), reshape(), and WIDTH.
void mouse (int button, int state, int x, int y)
Definition at line 183 of file artvertiser.cpp.
References cnt, label, lbuttonDown, and NUMARTVERTS.
Referenced by main().
static void photo_draw (void) [static]
The paint callback during photometric calibration and augmentation. In this case, we have access to 3D data. Thus, we can augment the calibration target with cool stuff.
Examples:
multigl.cpp.
Definition at line 618 of file artvertiser.cpp.
References artverts(), CalibModel::augm, augment, avi_capture, avi_frame, avi_image, avi_play, avi_play_init, MultiGrab::cams, cnt, current_cam, cvmGet(), LightMap::disableShader(), drawBackground(), LightMap::enableShader(), fade, fadeSpeed, PerspectiveProjection::flip(), format, foundMatch, frameOK, ftglFont, CamAugmentation::GetObjectToWorld(), CamAugmentation::GetProjectionMatrix(), PerspectiveCamera::getWorldToEyeMat(), HEIGHT, image, CalibModel::image, imageID, IsBGR, LightMap::isReady(), label, PerspectiveCamera::loadTdir(), Mat3x4::m, M_PI, CalibModel::map, CamCalibration::Mat3x4Mul(), MultiGrab::model, Mat3x4::mul(), roiVec, PerspectiveCamera::setGlModelView(), PerspectiveProjection::setGlProjection(), PerspectiveProjection::setPlanes(), Mat3x4::setRotate(), Mat3x4::setTranslate(), PerspectiveCamera::setWorldToEyeMat(), and WIDTH.
Referenced by photo_start().
static void photo_idle () [static]
GLUT calls this during photometric calibration or augmentation phase when there's nothing else to do. This function does the 2D detection and bundle adjusts the 3D pose of the calibration pattern.
Examples:
multigl.cpp.
Definition at line 892 of file artvertiser.cpp.
References CamAugmentation::Accomodate(), add_detected_homography(), CamAugmentation::AddHomography(), CalibModel::augm, MultiGrab::cams, CamAugmentation::Clear(), current_cam, frameOK, CamAugmentation::GetObjectToWorld(), MultiGrab::grabFrames(), MultiGrab::model, and IplTexture::setImage().
Referenced by photo_start().
static void photo_start () [static]
Starts photometric calibration.
Examples:
multigl.cpp.
Definition at line 930 of file artvertiser.cpp.
References photo_draw(), and photo_idle().
Referenced by geom_calib_idle(), and geom_calib_start().
static std::vector<int> readROI (const char * filename) [static]
Definition at line 226 of file artvertiser.cpp.
Referenced by init().
static void reshape (int width, int height) [static]
GLUT callback on window size change.
Examples:
multigl.cpp.
Definition at line 261 of file artvertiser.cpp.
References HEIGHT, and WIDTH.
Referenced by main().
static void usage (const char * s) [static]
Print a command line help and exit.
Examples:
augment3d.cpp, fullcalib.cpp, multicam.cpp, multigl.cpp, and singlecalib.cpp.
Definition at line 273 of file artvertiser.cpp.
Referenced by init(), and main().
Variable Documentation
int augment = 0
Examples:
augment3d.cpp.
Definition at line 122 of file artvertiser.cpp.
Referenced by keyboard(), main(), and photo_draw().
CvCapture* avi_capture = 0
Definition at line 80 of file artvertiser.cpp.
Referenced by init(), and photo_draw().
IplImage* avi_frame = 0
Definition at line 82 of file artvertiser.cpp.
Referenced by photo_draw().
IplImage* avi_image = 0
Definition at line 81 of file artvertiser.cpp.
Referenced by photo_draw().
int avi_init = 0
Definition at line 120 of file artvertiser.cpp.
bool avi_play = false
Definition at line 112 of file artvertiser.cpp.
Referenced by init(), keyboard(), and photo_draw().
bool avi_play_init = false
Definition at line 113 of file artvertiser.cpp.
Referenced by photo_draw().
bool cacheLight = false
Examples:
multigl.cpp.
Definition at line 109 of file artvertiser.cpp.
Referenced by init(), and photo_start().
CamCalibration* calib = 0
Examples:
augment3d.cpp, fullcalib.cpp, multicam.cpp, multigl.cpp, and singlecalib.cpp.
Definition at line 74 of file artvertiser.cpp.
Referenced by geometric_calibration(), and main().
CvCapture* capture = 0
Examples:
augment3d.cpp, fullcalib.cpp, and singlecalib.cpp.
Definition at line 79 of file artvertiser.cpp.
Referenced by main().
int cnt = 0
Definition at line 123 of file artvertiser.cpp.
Referenced by keyboard(), mouse(), and photo_draw().
int current_cam = 0
Examples:
multigl.cpp.
Definition at line 119 of file artvertiser.cpp.
Referenced by geom_calib_draw(), geom_calib_idle(), keyboard(), photo_draw(), and photo_idle().
bool dynamicLight = false
Examples:
multigl.cpp.
Definition at line 110 of file artvertiser.cpp.
Referenced by keyboard(), and photo_idle().
float fade = 0.0
Definition at line 155 of file artvertiser.cpp.
Referenced by photo_draw().
float fadeSpeed = 2.0
Definition at line 156 of file artvertiser.cpp.
Referenced by photo_draw().
CvFont font
Examples:
singlecalib.cpp.
Definition at line 131 of file artvertiser.cpp.
Referenced by acquire_model().
CvFont fontbold
Examples:
singlecalib.cpp.
Definition at line 131 of file artvertiser.cpp.
Referenced by acquire_model().
GLenum format
Definition at line 134 of file artvertiser.cpp.
Referenced by IplTexture::loadTexture(), and photo_draw().
int foundMatch = 0
Definition at line 121 of file artvertiser.cpp.
Referenced by photo_draw().
bool frameOK = false
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 108 of file artvertiser.cpp.
Referenced by photo_draw(), photo_idle(), and photometric_calibration().
IplTexture* frameTexture = 0
Examples:
multigl.cpp.
Definition at line 76 of file artvertiser.cpp.
FTFont* ftglFont [static]
Definition at line 153 of file artvertiser.cpp.
Referenced by main(), and photo_draw().
int geom_calib_nb_homography
Examples:
multigl.cpp.
Definition at line 118 of file artvertiser.cpp.
Referenced by geom_calib_idle(), and geom_calib_start().
IplImage* image = 0
Definition at line 78 of file artvertiser.cpp.
Referenced by PerspectiveProjection::getUndistortMap(), planar_object_recognizer::match_points(), photo_draw(), CamCalibration::PlotPointsToImagesAfterOptimization(), planar_object_recognizer::preprocess_points(), planar_object_recognizer::save_one_image_per_match_input_to_model(), planar_object_recognizer::save_one_image_per_match_model_to_input(), and LightMap::saveImage().
IplImage* image1 = cvLoadImage("artvert1.png")
Definition at line 85 of file artvertiser.cpp.
Referenced by init().
IplImage* image2 = cvLoadImage("artvert2.png")
Definition at line 86 of file artvertiser.cpp.
Referenced by init().
IplImage* image3 = cvLoadImage("artvert3.png")
Definition at line 87 of file artvertiser.cpp.
Referenced by init().
IplImage* image4 = cvLoadImage("artvert4.png")
Definition at line 88 of file artvertiser.cpp.
Referenced by init().
IplImage* image5 = cvLoadImage("artvert5.png")
Definition at line 89 of file artvertiser.cpp.
Referenced by init().
char* image_path
Definition at line 126 of file artvertiser.cpp.
Referenced by init().
GLuint imageID
Definition at line 135 of file artvertiser.cpp.
Referenced by photo_draw().
bool label = false
Definition at line 115 of file artvertiser.cpp.
Referenced by mouse(), and photo_draw().
bool lbuttonDown = false
Definition at line 114 of file artvertiser.cpp.
Referenced by mouse().
MultiGrab* multi = 0
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 72 of file artvertiser.cpp.
Referenced by main().
int nbLightMeasures = 0
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 117 of file artvertiser.cpp.
Referenced by photo_idle(), photo_start(), and photometric_calibration().
CvPoint projPts[4]
Examples:
fullcalib.cpp, and multicam.cpp.
Definition at line 75 of file artvertiser.cpp.
Referenced by augment_scene().
std::vector<int> roiVec
Definition at line 124 of file artvertiser.cpp.
Referenced by init(), and photo_draw().
bool sphereObject = false
Examples:
multigl.cpp.
Definition at line 111 of file artvertiser.cpp.
Referenced by keyboard(), and photo_draw().
IplTexture* tex = 0
Examples:
multigl.cpp.
Definition at line 77 of file artvertiser.cpp.