bazar: /home/julian/devel/artvertiser/garfeild/calib/camera.cpp File Reference
camera.cpp File Reference
#include <fstream>
#include <iostream>
#include <string.h>
#include "camera.h"
#include "matvec.h"
Classes
struct GuessMode
Functions
static void get3x3MulWithTransposed (const double m[3][4], double mmt[3][3])
static double diag (double x, double y)
static double diagDiff (const GuessMode &m, double dx, double dy)
ostream & operator<< (ostream &os, const PerspectiveProjection &cam)
ostream & operator<< (ostream &os, const PerspectiveCamera &cam)
Function Documentation
static double diag (double x, double y) [static]
Definition at line 431 of file camera.cpp.
Referenced by diagDiff().
static double diagDiff (const GuessMode & m, double dx, double dy) [static]
Definition at line 436 of file camera.cpp.
References diag(), GuessMode::h, and GuessMode::w.
Referenced by projection_matrix::load_tdir(), and PerspectiveCamera::loadTdir().
static void get3x3MulWithTransposed (const double m[3][4], double mmt[3][3]) [static]
Definition at line 265 of file camera.cpp.
Referenced by PerspectiveCamera::loadTdir().
ostream& operator<< (ostream & os, const PerspectiveCamera & cam)
Definition at line 556 of file camera.cpp.
References PerspectiveCamera::getWorldToEyeMat().
ostream& operator<< (ostream & os, const PerspectiveProjection & cam)
Definition at line 542 of file camera.cpp.
References PerspectiveProjection::cx, PerspectiveProjection::cy, PerspectiveProjection::f, PerspectiveProjection::farPlane, PerspectiveProjection::g, PerspectiveProjection::height, PerspectiveProjection::nearPlane, PerspectiveProjection::s, and PerspectiveProjection::width.