bazar: CvGrowMat Class Reference
CvGrowMat Class Reference
#include <growmat.h>
Public Member Functions
CvGrowMat (int maxlines, int maxcols, int type)
~CvGrowMat ()
void resize (int lines, int cols)
Detailed Description
Definition at line 6 of file growmat.h.
Constructor & Destructor Documentation
CvGrowMat::CvGrowMat (int maxlines, int maxcols, int type)
Definition at line 3 of file growmat.cpp.
CvGrowMat::~CvGrowMat ()
Definition at line 10 of file growmat.cpp.
Member Function Documentation
void CvGrowMat::resize (int lines, int cols)
Definition at line 15 of file growmat.cpp.
Referenced by LightMap::addNormalCalib(), LightMap::load(), loadMat(), and LightMap::setCamNum().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/starter/math/growmat.h
/home/julian/devel/artvertiser/starter/math/growmat.cpp