bazar: affinity Class Reference
affinity Class Reference
[Starter: Basic structures and mathematical tools]
#include <affinity.h>
Public Member Functions
affinity (void)
affinity (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3)
~affinity ()
bool estimate (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3)
void transform_point (float u, float v, float *up, float *vp)
void transform_point (double u, double v, double *up, double *vp)
void compute_cvGetQuandrangleSubPix_transform (CvMat *A_quadrangle, int width, int height)
float cvmGet (const int i, const int j)
void cvmSet (const int i, const int j, const float val)
void cvmSet (const int i, const int j, const double val)
Friends
ostream & operator<< (ostream &o, const affinity &A)
float cvmGet (const affinity *A, const int i, const int j)
void cvmSet (const affinity *A, const int i, const int j, const float val)
void cvmSet (const affinity *A, const int i, const int j, const double val)
void mcvGetQuadrangleSubPix (IplImage *src, IplImage *dest, affinity *A, int fill_outliers=0, CvScalar fill_value=cvScalarAll(0))
Detailed Description
Affine transformation.
Definition at line 33 of file affinity.h.
Constructor & Destructor Documentation
affinity::affinity (void)
Definition at line 24 of file affinity.cpp.
affinity::affinity (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3)
Definition at line 29 of file affinity.cpp.
References estimate().
affinity::~affinity ()
Definition at line 59 of file affinity.cpp.
Member Function Documentation
bool affinity::estimate (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3)
Definition at line 75 of file affinity.cpp.
References cvmGet(), and cvmSet().
Referenced by affinity(), and planar_object_recognizer::estimate_affine_transformation().
void affinity::transform_point (float u, float v, float * up, float * vp)
Definition at line 116 of file affinity.cpp.
References cvmGet().
Referenced by planar_object_recognizer::compute_support_for_affine_transformation(), and planar_object_recognizer::detect().
void affinity::transform_point (double u, double v, double * up, double * vp)
Definition at line 122 of file affinity.cpp.
References cvmGet().
void affinity::compute_cvGetQuandrangleSubPix_transform (CvMat * A_quadrangle, int width, int height)
Definition at line 128 of file affinity.cpp.
References cvmGet(), and cvmSet().
float affinity::cvmGet (const int i, const int j) [inline]
Definition at line 71 of file affinity.h.
Referenced by compute_cvGetQuandrangleSubPix_transform(), estimate(), planar_object_recognizer::estimate_homographic_transformation_nonlinear_method(), operator<<(), and transform_point().
void affinity::cvmSet (const int i, const int j, const float val) [inline]
Definition at line 76 of file affinity.h.
Referenced by compute_cvGetQuandrangleSubPix_transform(), and estimate().
void affinity::cvmSet (const int i, const int j, const double val) [inline]
Definition at line 81 of file affinity.h.
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const affinity & A) [friend]
Definition at line 67 of file affinity.cpp.
float cvmGet (const affinity * A, const int i, const int j) [friend]
Definition at line 86 of file affinity.h.
void cvmSet (const affinity * A, const int i, const int j, const float val) [friend]
Definition at line 93 of file affinity.h.
void cvmSet (const affinity * A, const int i, const int j, const double val) [friend]
Definition at line 100 of file affinity.h.
void mcvGetQuadrangleSubPix (IplImage * src, IplImage * dest, affinity * A, int fill_outliers = 0, CvScalar fill_value = cvScalarAll(0)) [friend]
Definition at line 141 of file affinity.cpp.
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/starter/geometry/affinity.h
/home/julian/devel/artvertiser/starter/geometry/affinity.cpp