bazar: homography Class Reference
homography Class Reference
[Starter: Basic structures and mathematical tools]
Static class for the estimation of homographies.
Provides functions to estimate the homography
from 4 point correspondences or
from n point correspondences.
#include <homography.h>
Public Member Functions
homography ()
homography (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3, float u4, float v4, float up4, float vp4)
~homography ()
bool estimate (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3, float u4, float v4, float up4, float vp4)
Estimates H from 4 point correspondences.
void set_match_number (int n)
Estimation from n correspondences. See homography description.
void add_match (float u, float v, float up, float vp)
void release_matches (void)
void estimate (void)
void transform_point (float u, float v, float *up, float *vp)
Computes H(u,v).
void transform_point (double u, double v, double *up, double *vp)
float cvmGet (const int i, const int j)
void cvmSet (const int i, const int j, const float val)
void cvmSet (const int i, const int j, const double val)
Friends
ostream & operator<< (ostream &o, const homography &H)
float cvmGet (const homography *H, const int i, const int j)
void cvmSet (const homography *H, const int i, const int j, const float val)
void cvmSet (const homography *H, const int i, const int j, const double val)
Detailed Description
Static class for the estimation of homographies.
Provides functions to estimate the homography
from 4 point correspondences or
from n point correspondences.
From 4 point correspondences: Use one of the estimate() functions:
homography::estimate(H, u1, v1, up1, vp1, u2, v2, up2, vp2, ...)
or
CvMat * H = homography::estimate(H, u1, v1, up1, vp1, u2, v2, up2, vp2, ...)
Estimates H using a linear method.
From n correspondences if H0 != NULL, it is used to initialize H. H0 can be an affinity matrix. c is the parameter of the Tukey robust estimator.
Definition at line 55 of file homography.h.
Constructor & Destructor Documentation
homography::homography (void)
Definition at line 33 of file homography.cpp.
homography::homography (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3, float u4, float v4, float up4, float vp4)
Definition at line 38 of file homography.cpp.
References estimate().
homography::~homography ()
Definition at line 51 of file homography.cpp.
Member Function Documentation
bool homography::estimate (float u1, float v1, float up1, float vp1, float u2, float v2, float up2, float vp2, float u3, float v3, float up3, float vp3, float u4, float v4, float up4, float vp4)
Estimates H from 4 point correspondences.
Definition at line 124 of file homography.cpp.
References add_match(), cvmGet(), and cvmSet().
Referenced by planar_object_recognizer::estimate_homographic_transformation_linear_method(), and LightCollector::genGrid().
void homography::set_match_number (int n)
Estimation from n correspondences. See homography description.
Definition at line 174 of file homography.cpp.
References release_matches().
Referenced by planar_object_recognizer::estimate_homographic_transformation_linear_method().
void homography::add_match (float u, float v, float up, float vp)
Definition at line 197 of file homography.cpp.
Referenced by estimate(), and planar_object_recognizer::estimate_homographic_transformation_linear_method().
void homography::release_matches (void)
Definition at line 190 of file homography.cpp.
Referenced by set_match_number().
void homography::estimate (void)
Definition at line 203 of file homography.cpp.
References cvmGet(), and cvmSet().
Referenced by homography().
void homography::transform_point (float u, float v, float * up, float * vp)
Computes H(u,v).
Definition at line 157 of file homography.cpp.
References cvmGet().
Referenced by planar_object_recognizer::detect(), and planar_object_recognizer::estimate_homographic_transformation_nonlinear_method().
void homography::transform_point (double u, double v, double * up, double * vp)
Definition at line 165 of file homography.cpp.
References cvmGet().
float homography::cvmGet (const int i, const int j) [inline]
Definition at line 108 of file homography.h.
Referenced by estimate(), operator<<(), CamCalibration::StoreHomographiesToFile(), and transform_point().
void homography::cvmSet (const int i, const int j, const float val) [inline]
Definition at line 113 of file homography.h.
Referenced by estimate(), planar_object_recognizer::estimate_homographic_transformation_nonlinear_method(), and CamCalibration::LoadHomographiesFromFile().
void homography::cvmSet (const int i, const int j, const double val) [inline]
Definition at line 118 of file homography.h.
Friends And Related Function Documentation
ostream& operator<< (ostream & o, const homography & H) [friend]
Definition at line 85 of file homography.cpp.
float cvmGet (const homography * H, const int i, const int j) [friend]
Definition at line 123 of file homography.h.
void cvmSet (const homography * H, const int i, const int j, const float val) [friend]
Definition at line 130 of file homography.h.
void cvmSet (const homography * H, const int i, const int j, const double val) [friend]
Definition at line 137 of file homography.h.
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/starter/geometry/homography.h
/home/julian/devel/artvertiser/starter/geometry/homography.cpp