bazar: example_generator Class Reference
example_generator Class Reference
[Viewsets]
Generates random representants of image classes.
#include <example_generator.h>
Public Member Functions
example_generator (void)
virtual ~example_generator ()
virtual vector
< image_class_example * > * generate_random_examples (void)
virtual void release_examples (void)
Detailed Description
Generates random representants of image classes.
The image classifiers can call the generate_random_examples function to generate the learning set. Use it when the learning set can be synthesized.
Definition at line 36 of file example_generator.h.
Constructor & Destructor Documentation
example_generator::example_generator (void) [inline]
Definition at line 39 of file example_generator.h.
virtual example_generator::~example_generator () [inline, virtual]
Definition at line 40 of file example_generator.h.
Member Function Documentation
virtual vector<image_class_example *>* example_generator::generate_random_examples (void) [inline, virtual]
Reimplemented in affine_image_generator.
Definition at line 42 of file example_generator.h.
Referenced by image_classification_tree::refine(), image_classification_forest::refine(), image_classification_tree::test(), and image_classification_forest::test().
virtual void example_generator::release_examples (void) [inline, virtual]
Reimplemented in affine_image_generator.
Definition at line 44 of file example_generator.h.
Referenced by image_classification_tree::refine(), image_classification_forest::refine(), image_classification_tree::test(), and image_classification_forest::test().
The documentation for this class was generated from the following file:
/home/julian/devel/artvertiser/garfeild/viewsets/example_generator.h