bazar: image_classification_tree Class Reference
image_classification_tree Class Reference
[Viewsets]
Image classifier tree.
#include <image_classification_tree.h>
Public Member Functions
image_classification_tree (LEARNPROGRESSION LearnProgress=0)
image_classification_tree (int image_width, int image_height, int class_number, int max_depth, LEARNPROGRESSION LearnProgress=0)
~image_classification_tree ()
bool load (string filename)
bool save (string filename)
virtual void refine (example_generator *vg, int call_number)
virtual void test (example_generator *vg, int call_number)
int recognize (image_class_example *pv, float *confidence=0, int dummy=0)
virtual float * posterior_probabilities (image_class_example *pv, int dummy=0)
void change_class_number_and_reset_probabilities (int new_class_number)
int node_number (void)
int leaves_number (void)
int actual_max_depth (void)
double entropy (void)
Public Attributes
image_classification_node * root
int max_depth
Detailed Description
Image classifier tree.
Definition at line 34 of file image_classification_tree.h.
Constructor & Destructor Documentation
image_classification_tree::image_classification_tree (LEARNPROGRESSION LearnProgress = 0)
Definition at line 52 of file image_classification_tree.cpp.
References root.
image_classification_tree::image_classification_tree (int image_width, int image_height, int class_number, int max_depth, LEARNPROGRESSION LearnProgress = 0)
Definition at line 59 of file image_classification_tree.cpp.
References max_depth, and root.
image_classification_tree::~image_classification_tree ()
Definition at line 136 of file image_classification_tree.cpp.
References root.
Member Function Documentation
bool image_classification_tree::load (string filename) [virtual]
Reimplemented from image_classifier.
Definition at line 69 of file image_classification_tree.cpp.
References image_classification_node::children, image_classification_node::children_index, image_classification_node::children_number, image_classifier::class_number, global_patch_size, image_classifier::image_height, image_classifier::image_width, image_classification_node::is_leaf(), max_depth, image_classification_node::parent, and root.
Referenced by image_classification_forest::load().
bool image_classification_tree::save (string filename) [virtual]
Reimplemented from image_classifier.
Definition at line 142 of file image_classification_tree.cpp.
References image_classifier::class_number, image_classifier::image_height, image_classifier::image_width, leaves_number(), max_depth, node_number(), and root.
void image_classification_tree::refine (example_generator * vg, int call_number) [virtual]
Implements image_classifier.
Definition at line 163 of file image_classification_tree.cpp.
References image_classification_node::child_index(), image_classification_node::children, example_generator::generate_random_examples(), image_classification_node::is_leaf(), image_classification_node::P, image_classification_node::reestimate_probabilities_recursive(), example_generator::release_examples(), and root.
void image_classification_tree::test (example_generator * vg, int call_number) [virtual]
Implements image_classifier.
Definition at line 191 of file image_classification_tree.cpp.
References image_classifier::class_number, example_generator::generate_random_examples(), recognize(), and example_generator::release_examples().
int image_classification_tree::recognize (image_class_example * pv, float * confidence = 0, int dummy = 0) [virtual]
Implements image_classifier.
Definition at line 240 of file image_classification_tree.cpp.
References image_classification_node::best_class, image_classification_node::child_index(), image_classification_node::children, image_classification_node::is_leaf(), image_classification_node::P, and root.
Referenced by test().
float * image_classification_tree::posterior_probabilities (image_class_example * pv, int dummy = 0) [virtual]
Implements image_classifier.
Definition at line 253 of file image_classification_tree.cpp.
References image_classification_node::children, image_classification_node::d1, image_classification_node::d2, image_classification_node::is_leaf(), image_classification_node::P, image_class_example::preprocessed, and root.
void image_classification_tree::change_class_number_and_reset_probabilities (int new_class_number)
Definition at line 298 of file image_classification_tree.cpp.
References image_classification_node::change_class_number_and_reset_probabilities(), and root.
int image_classification_tree::node_number (void)
Definition at line 270 of file image_classification_tree.cpp.
References image_classification_node::node_number(), and root.
Referenced by image_classification_forest::create_trees_at_random(), and save().
int image_classification_tree::leaves_number (void)
Definition at line 275 of file image_classification_tree.cpp.
References image_classification_node::leaves_number(), and root.
Referenced by save().
int image_classification_tree::actual_max_depth (void)
Definition at line 280 of file image_classification_tree.cpp.
double image_classification_tree::entropy (void)
Definition at line 285 of file image_classification_tree.cpp.
Member Data Documentation
image_classification_node* image_classification_tree::root
Definition at line 61 of file image_classification_tree.h.
Referenced by change_class_number_and_reset_probabilities(), image_classification_forest::create_trees_at_random(), image_classification_tree(), leaves_number(), load(), node_number(), posterior_probabilities(), recognize(), refine(), save(), and ~image_classification_tree().
int image_classification_tree::max_depth
Definition at line 62 of file image_classification_tree.h.
Referenced by image_classification_tree(), load(), and save().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/viewsets/image_classification_tree.h
/home/julian/devel/artvertiser/garfeild/viewsets/image_classification_tree.cpp