bazar: LightMap Class Reference
LightMap Class Reference
[Photometric Calibration]
Irradiance map computation, storage and augmentation.
#include <lightmap.h>
Public Member Functions
LightMap ()
~LightMap ()
LightMap (const LightMap &a)
bool init (int nbCam, IplImage *model, float corners[4][2], int nx, int ny)
void setCamNum (int n)
bool initGL ()
void enableShader (int cam, CvMat *obj2world)
void disableShader ()
bool load (const char *lightParamsFN="lightParams.mat", const char *normalsFN="normals.mat")
bool save (const char *lightParamsFN="lightParams.mat", const char *normalsFN="normals.mat")
bool addNormal (float normal[3], LightCollector &lc, int cam)
calls addNormalCalib if the system is not yet solved, or addNormallightMap otherwise.
bool addNormalCalib (float normal[3], LightCollector &lc, int cam)
Add a normal for future light map computation.
bool addNormalLightMap (float normal[3], LightCollector &lc, int cam)
Update the current light map with given observation.
bool computeLightParams ()
bool isReady ()
return true when computeLightParams() has succeeded.
bool saveImage (const char *filename)
const float * getGain (int cam)
return the (B,G,R) gain of a camera.
const float * getBias (int cam)
return the (B,G,R) bias of a camera.
CvScalar readMap (const float normal[3])
returns the irradiance for a given normal.
int nbNormals () const
the number of normals measured that'll be used by computeLightParams.
Public Attributes
IplTexture map
Contains the irradiance map. Read it with readMap, update it with addNormal.
LightCollector reflc
Classes
struct Observation
Detailed Description
Irradiance map computation, storage and augmentation.
Author:
Julien Pilet
This class computes a environmental radiance map and uses OpenGL to augment 3D objects accordingly.
The process to build a light map is the following: After geometric calibration, it becomes possible to turn an homography into a 3D pose (see CamAugmentation). Thus, when the planar target is detected on an image, it is possible to compute its normal in a reference coordinate system. It is also possible to compare its color with the model one. After collecting many views, a simple linear system computes gain and bias of each camera and the irradiance for each normal.
All of this is done under lambertian assumption and might not behave very well in presence of specularities, specially in a multi-camera environment.
Relighting 3D objects for augmentation can done by GPU using a vertex and a pixel shader.
Definition at line 42 of file lightmap.h.
Constructor & Destructor Documentation
LightMap::LightMap ()
Definition at line 16 of file lightmap.cpp.
LightMap::~LightMap ()
Definition at line 37 of file lightmap.cpp.
References IplTexture::getIm(), and map.
LightMap::LightMap (const LightMap & a)
Definition at line 25 of file lightmap.cpp.
References ARB, LightCollector::copy(), IplTexture::getIm(), map, reflc, and IplTexture::setImage().
Member Function Documentation
bool LightMap::init (int nbCam, IplImage * model, float corners[4][2], int nx, int ny)
Definition at line 45 of file lightmap.cpp.
References LightCollector::averageImage(), LightCollector::avg, LightCollector::genGrid(), IplTexture::getIm(), map, reflc, setCamNum(), and IplTexture::setImage().
Referenced by CalibModel::buildCached().
void LightMap::setCamNum (int n)
Definition at line 416 of file lightmap.cpp.
References CvGrowMat::resize().
Referenced by init().
bool LightMap::initGL ()
Definition at line 259 of file lightmap.cpp.
Referenced by enableShader().
void LightMap::enableShader (int cam, CvMat * obj2world)
Examples:
multigl.cpp.
Definition at line 337 of file lightmap.cpp.
References initGL(), IplTexture::loadTexture(), and map.
Referenced by photo_draw().
void LightMap::disableShader ()
Examples:
multigl.cpp.
Definition at line 407 of file lightmap.cpp.
References IplTexture::disableTexture(), and map.
Referenced by photo_draw().
bool LightMap::load (const char * lightParamsFN = "lightParams.mat", const char * normalsFN = "normals.mat")
Examples:
fullcalib.cpp, and multigl.cpp.
Definition at line 677 of file lightmap.cpp.
References loadMat(), and CvGrowMat::resize().
Referenced by photo_start(), and photometric_calibration().
bool LightMap::save (const char * lightParamsFN = "lightParams.mat", const char * normalsFN = "normals.mat")
Examples:
fullcalib.cpp, and multigl.cpp.
Definition at line 605 of file lightmap.cpp.
References saveMat().
Referenced by photo_idle(), and photometric_calibration().
bool LightMap::addNormal (float normal[3], LightCollector & lc, int cam)
calls addNormalCalib if the system is not yet solved, or addNormallightMap otherwise.
Examples:
fullcalib.cpp, and multigl.cpp.
Definition at line 121 of file lightmap.cpp.
References addNormalCalib(), and addNormalLightMap().
Referenced by photo_idle(), and photometric_calibration().
bool LightMap::addNormalCalib (float normal[3], LightCollector & lc, int cam)
Add a normal for future light map computation.
Definition at line 439 of file lightmap.cpp.
References LightCollector::avg, LightCollector::avgChannels, LightCollector::nbTri, normalize(), reflc, and CvGrowMat::resize().
Referenced by addNormal().
bool LightMap::addNormalLightMap (float normal[3], LightCollector & lc, int cam)
Update the current light map with given observation.
Definition at line 143 of file lightmap.cpp.
References LightCollector::cmpWithRef(), getBias(), getGain(), IplTexture::getIm(), map, and reflc.
Referenced by addNormal().
bool LightMap::computeLightParams ()
Compute the light map using all available observations, previously added with addNormalCalib ir addNormal.
Examples:
fullcalib.cpp, and multigl.cpp.
Definition at line 611 of file lightmap.cpp.
References LightCollector::avgChannels, IplTexture::getIm(), map, and reflc.
Referenced by photo_idle(), and photometric_calibration().
bool LightMap::isReady () [inline]
return true when computeLightParams() has succeeded.
Examples:
fullcalib.cpp, multicam.cpp, and multigl.cpp.
Definition at line 73 of file lightmap.h.
Referenced by augment_scene(), getBias(), getGain(), photo_draw(), photo_idle(), photometric_calibration(), and readMap().
bool LightMap::saveImage (const char * filename)
Definition at line 712 of file lightmap.cpp.
References IplTexture::getIm(), image, and map.
const float * LightMap::getGain (int cam)
return the (B,G,R) gain of a camera.
Examples:
fullcalib.cpp, multicam.cpp, and multigl.cpp.
Definition at line 129 of file lightmap.cpp.
References isReady().
Referenced by addNormalLightMap(), augment_scene(), photo_draw(), and photometric_calibration().
const float * LightMap::getBias (int cam)
return the (B,G,R) bias of a camera.
Examples:
fullcalib.cpp, multicam.cpp, and multigl.cpp.
Definition at line 136 of file lightmap.cpp.
References isReady().
Referenced by addNormalLightMap(), augment_scene(), photo_draw(), and photometric_calibration().
CvScalar LightMap::readMap (const float normal[3])
returns the irradiance for a given normal.
Examples:
fullcalib.cpp, multicam.cpp, and multigl.cpp.
Definition at line 104 of file lightmap.cpp.
References IplTexture::getIm(), isReady(), and map.
Referenced by augment_scene(), and photo_draw().
int LightMap::nbNormals () const [inline]
the number of normals measured that'll be used by computeLightParams.
Examples:
multigl.cpp.
Definition at line 91 of file lightmap.h.
Referenced by photo_idle().
Member Data Documentation
IplTexture LightMap::map
Contains the irradiance map. Read it with readMap, update it with addNormal.
Examples:
fullcalib.cpp, and multigl.cpp.
Definition at line 76 of file lightmap.h.
Referenced by addNormalLightMap(), computeLightParams(), disableShader(), enableShader(), init(), LightMap(), photo_draw(), photometric_calibration(), readMap(), saveImage(), and ~LightMap().
LightCollector LightMap::reflc
Examples:
fullcalib.cpp.
Definition at line 78 of file lightmap.h.
Referenced by addNormalCalib(), addNormalLightMap(), MultiGrab::allocLightCollector(), computeLightParams(), init(), LightMap(), and photometric_calibration().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/lightcalib/lightmap.h
/home/julian/devel/artvertiser/garfeild/lightcalib/lightmap.cpp