bazar: keypoint_orientation_corrector Class Reference
keypoint_orientation_corrector Class Reference
[Feature points detection]
Normalize local patches against rotation.
#include <keypoint_orientation_corrector.h>
Public Member Functions
keypoint_orientation_corrector (int width, int height, int neighborhood_size, int nbLev)
~keypoint_orientation_corrector ()
void compute_gradient_images (IplImage *image, IplImage **Ix, IplImage **Iy)
int orientation_bucket_index (const IplImage *_Ix, const IplImage *_Iy, const int u, const int v)
Returns the estimated orientation (actually the corresponding bucket index).
int optimized_orientation_bucket_index (const IplImage *_Ix, const IplImage *_Iy, const int u, const int v)
Optimized version.
float estimate_orientation_in_radians (IplImage *image, int u, int v, IplImage *_Ix, IplImage *_Iy)
returns the estimated orientation expressed in radians
int correct_orientation (IplImage *image, int u, int v, IplImage *rotated_neighborhood, IplImage *Ix, IplImage *Iy, int level)
Rotates the (u,v) neighborhood and returns the estimated orientation (actually the corresponding bucket index):.
int correct_orientationf (IplImage *image, float u, float v, IplImage *rotated_neighborhood, float orientation_in_radians, int level)
Static Public Attributes
static bool subpixel_rotate = false
static const int ANGLE_QUANTUM = 20
static const int ANGLE_BUCKET_NUMBER = 360 / ANGLE_QUANTUM
Detailed Description
Normalize local patches against rotation.
Definition at line 30 of file keypoint_orientation_corrector.h.
Constructor & Destructor Documentation
keypoint_orientation_corrector::keypoint_orientation_corrector (int width, int height, int neighborhood_size, int nbLev)
Definition at line 40 of file keypoint_orientation_corrector.cpp.
References ANGLE_BUCKET_NUMBER.
keypoint_orientation_corrector::~keypoint_orientation_corrector ()
Definition at line 130 of file keypoint_orientation_corrector.cpp.
References ANGLE_BUCKET_NUMBER.
Member Function Documentation
void keypoint_orientation_corrector::compute_gradient_images (IplImage * image, IplImage ** Ix, IplImage ** Iy)
Definition at line 140 of file keypoint_orientation_corrector.cpp.
References DERIVATIVES_KERNEL_SIZE.
int keypoint_orientation_corrector::orientation_bucket_index (const IplImage * _Ix, const IplImage * _Iy, const int u, const int v)
Returns the estimated orientation (actually the corresponding bucket index).
Definition at line 149 of file keypoint_orientation_corrector.cpp.
References ANGLE_BUCKET_NUMBER, ATAN2_TABLE_INDEX, GRADIENT_SHIFT, and MAX_GRADIENT.
Referenced by correct_orientation(), estimate_orientation_in_radians(), and optimized_orientation_bucket_index().
int keypoint_orientation_corrector::optimized_orientation_bucket_index (const IplImage * _Ix, const IplImage * _Iy, const int u, const int v)
Optimized version.
Definition at line 197 of file keypoint_orientation_corrector.cpp.
References ANGLE_BUCKET_NUMBER, ATAN2_TABLE_INDEX, GRADIENT_SHIFT, MAX_GRADIENT, and orientation_bucket_index().
float keypoint_orientation_corrector::estimate_orientation_in_radians (IplImage * image, int u, int v, IplImage * _Ix, IplImage * _Iy)
returns the estimated orientation expressed in radians
Definition at line 317 of file keypoint_orientation_corrector.cpp.
References ANGLE_BUCKET_NUMBER, and orientation_bucket_index().
Referenced by affine_image_generator::preprocess_point_view().
int keypoint_orientation_corrector::correct_orientation (IplImage * image, int u, int v, IplImage * rotated_neighborhood, IplImage * Ix, IplImage * Iy, int level)
Rotates the (u,v) neighborhood and returns the estimated orientation (actually the corresponding bucket index):.
Definition at line 328 of file keypoint_orientation_corrector.cpp.
References orientation_bucket_index().
int keypoint_orientation_corrector::correct_orientationf (IplImage * image, float u, float v, IplImage * rotated_neighborhood, float orientation_in_radians, int level)
Definition at line 339 of file keypoint_orientation_corrector.cpp.
References ANGLE_BUCKET_NUMBER, and subpixel_rotate.
Referenced by affine_image_generator::preprocess_point_view().
Member Data Documentation
bool keypoint_orientation_corrector::subpixel_rotate = false [static]
Definition at line 55 of file keypoint_orientation_corrector.h.
Referenced by correct_orientationf().
const int keypoint_orientation_corrector::ANGLE_QUANTUM = 20 [static]
Definition at line 57 of file keypoint_orientation_corrector.h.
const int keypoint_orientation_corrector::ANGLE_BUCKET_NUMBER = 360 / ANGLE_QUANTUM [static]
Definition at line 58 of file keypoint_orientation_corrector.h.
Referenced by correct_orientationf(), estimate_orientation_in_radians(), keypoint_orientation_corrector(), optimized_orientation_bucket_index(), orientation_bucket_index(), and ~keypoint_orientation_corrector().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/keypoints/keypoint_orientation_corrector.h
/home/julian/devel/artvertiser/garfeild/keypoints/keypoint_orientation_corrector.cpp