bazar: planar_object_recognizer Class Reference
planar_object_recognizer Class Reference
[Viewsets]
Planar object detector.
#include <planar_object_recognizer.h>
Functions for fine tuning:
int sample_number_for_refining
void use_bins_when_creating_model_points (void)
Activate bins when detecting model points (Default).
void dont_use_bins_when_creating_model_points (void)
Disactivate bins when detecting model points.
void use_bins_when_detecting_input_image_points (void)
Activate bins when detecting input image points (Default).
void dont_use_bins_when_detecting_input_image_points (void)
Disactivate bins when detecting model points.
void set_noise_level (int noise_level)
Default = 20.
void set_use_random_background (bool use_random_background)
Default = false;.
void set_range_variation_for_theta (float min_theta, float max_theta)
Global rotation. Default = [0 : 2Pi].
void set_range_variation_for_phi (float min_phi, float max_phi)
Skew. Default = [0 : Pi].
void independent_scaling (float min_lambda1, float max_lambda1, float min_lambda2, float max_lambda2)
Default method. Between 0.5 : 1.5 for both.
void constrained_scaling (float min_lambda1, float max_lambda1, float min_lambda2, float max_lambda2, float min_l1_l2, float max_l1_l2)
Constrained scaling. Adds a constraint on the range of the product of l1 and l2.
void use_orientation_correction (void)
Default method.
void dont_use_orientation_correction (void)
void set_max_depth (int p_max_depth)
Default = 10.
void set_sample_number_for_refining (int sample_number)
Sample number for the refine step (default = 1000):.
IplImage * model_and_input_images
int x0
int y0
int u_input_image
int v_input_image
void save_patch_before_and_after_correction (IplImage *image, int u, int v, int patch_size, image_class_example *pv, int point_index, int call_number)
The following functions are useful for visualization only:.
void concat_model_and_input_images (IplImage *input_image, bool p_draw_model_image=true)
void draw_points (int line_width=1)
void draw_model_points (int line_width=1)
void draw_input_image_points (int line_width=1)
void draw_matches (int line_width=2)
void draw_inlier_matches (int line_width=1)
void draw_model (void)
Public Member Functions
planar_object_recognizer ()
empty constructor. call build, load or buildWithCache before use
planar_object_recognizer (string directory_name)
Create from the data stored in the directory directory_name.
~planar_object_recognizer (void)
bool build_with_cache (string filename, int max_point_number_on_model, int patch_size, int yape_radius, int tree_number, int nbLev, LEARNPROGRESSION LearnProgress=0)
Build the model and save it on disk.
bool build (IplImage *model_image, int max_point_number_on_model, int patch_size, int yape_radius, int tree_number, int nbLev, LEARNPROGRESSION LearnProgress=0, int *roi=0)
void learn (int max_point_number_on_model, int patch_size, int yape_radius, int tree_number, int nbLev=5, LEARNPROGRESSION LearnProgress=0)
Create the point recognizer (see forest field).
void save (string directory_name)
Save data in the given directory. The directory must exist.
bool load (string directory_name)
load data from a given directory.
bool detect (IplImage *input_image)
Detect the object in the given input image.
void set_max_detected_pts (int max)
set the maximum number of points we want to detect
IplImage * create_result_image (IplImage *input_image, bool p_draw_points, bool p_draw_matches, bool p_draw_object, bool p_draw_model_image, int line_width=2)
For visualization.
void debug_model_point (int p_index_of_model_point_to_debug)
For debugging: save generated patches for a particular point in dir patches, before and after orientation correction.
void save_one_image_per_match (IplImage *input_image, const char *matches_dir)
For debugging: save one image per match in dir matches.
void save_one_image_per_match_model_to_input (IplImage *input_image, const char *matches_dir)
void save_one_image_per_match_input_to_model (IplImage *input_image, const char *matches_dir)
void initialize (void)
Function called by the 2 constructors.
pair< object_keypoint, int > * search_for_existing_model_point (vector< pair< object_keypoint, int > > *tmp_model_points, float cu, float cv, int scale)
void detect_most_stable_model_points (int max_point_number_on_model, int patch_size, int view_number, double min_view_rate, LEARNPROGRESSION LearnProgress=0)
void save_image_of_model_points (int patch_size, char *filename=0)
int compute_support_for_affine_transformation (affinity *A)
bool three_random_correspondences (int *n1, int *n2, int *n3)
bool valid (affinity *A)
void default_settings (void)
Some parameters for fine tuning: Called by the 2 constructors.
void check_target_size (IplImage *image)
Functions called by the detect() function
void detect_points (IplImage *input_image)
void preprocess_points (void)
void match_points (bool fill_match_struct=true)
bool estimate_affine_transformation (void)
bool estimate_homographic_transformation_linear_method (void)
bool estimate_homographic_transformation_nonlinear_method (void)
Public Attributes
object_keypoint * model_points
keypoints on the object.
int model_point_number
keypoint * detected_points
Detected keypoints in the input image.
int detected_point_number
image_class_example * detected_point_views
float * match_probabilities [hard_max_detected_pts]
Match probabilities for each detected keypoint.
image_object_point_match matches [hard_max_detected_pts]
Matches between the detected keypoints, and the model keypoints.
int match_number
bool object_is_detected
affinity * affine_motion
homography * H
ls_minimizer2 * homography_estimator
float detected_u_corner1
float detected_v_corner1
float detected_u_corner2
float detected_v_corner2
float detected_u_corner3
float detected_v_corner3
float detected_u_corner4
float detected_v_corner4
pyr_yape * point_detector
affine_image_generator new_images_generator
object_view * object_input_view
image_classification_forest * forest
Image classifier.
int max_detected_pts
int max_depth
bool use_bins_for_model_points
bool use_bins_for_input_image
int index_of_model_point_to_debug
int views_number
number of generated views for finding stable points
double min_view_rate
minimum visible rate for determining stable keypoints
double keypoint_distance_threshold
float match_score_threshold
float ransac_dist_threshold
float non_linear_refine_threshold
Distance threshold, in pixels, for non-linear refinement.
int max_ransac_iterations
maximum iteration number for RANSAC
int ransac_stop_support
Detailed Description
Planar object detector.
This class can learn a planar surface and recognize its feature points on a new image.
Examples:
augment3d.cpp, filedetect.cpp, fullcalib.cpp, multicam.cpp, multigl.cpp, and singlecalib.cpp.
Definition at line 49 of file planar_object_recognizer.h.
Constructor & Destructor Documentation
planar_object_recognizer::planar_object_recognizer ()
empty constructor. call build, load or buildWithCache before use
Definition at line 35 of file planar_object_recognizer.cpp.
References affine_motion, default_settings(), detected_point_views, detected_points, forest, H, hard_max_detected_pts, homography_estimator, match_score_threshold, max_ransac_iterations, model_and_input_images, model_points, non_linear_refine_threshold, object_input_view, point_detector, ransac_dist_threshold, and ransac_stop_support.
planar_object_recognizer::planar_object_recognizer (string directory_name)
Create from the data stored in the directory directory_name.
Definition at line 204 of file planar_object_recognizer.cpp.
References forest, load(), and model_points.
planar_object_recognizer::~planar_object_recognizer (void)
Definition at line 312 of file planar_object_recognizer.cpp.
References affine_motion, detected_point_views, detected_points, forest, H, hard_max_detected_pts, homography_estimator, match_probabilities, model_points, object_input_view, and point_detector.
Member Function Documentation
bool planar_object_recognizer::build_with_cache (string filename, int max_point_number_on_model, int patch_size, int yape_radius, int tree_number, int nbLev, LEARNPROGRESSION LearnProgress = 0)
Build the model and save it on disk.
Returns:
true on success, false on failure
Examples:
augment3d.cpp, filedetect.cpp, and singlecalib.cpp.
Definition at line 165 of file planar_object_recognizer.cpp.
References initialize(), learn(), load(), mcvLoadImage(), new_images_generator, save(), affine_image_generator::set_gaussian_smoothing_kernel_size(), affine_image_generator::set_level_number(), affine_image_generator::set_original_image(), and affine_image_generator::set_patch_size().
Referenced by CalibModel::buildCached(), and main().
bool planar_object_recognizer::build (IplImage * model_image, int max_point_number_on_model, int patch_size, int yape_radius, int tree_number, int nbLev, LEARNPROGRESSION LearnProgress = 0, int * roi = 0)
Build a classifier from the given model image. The result is not saved.
Returns:
true on success, false on failure.
Examples:
singlecalib.cpp.
Definition at line 128 of file planar_object_recognizer.cpp.
References initialize(), learn(), new_images_generator, affine_image_generator::set_gaussian_smoothing_kernel_size(), affine_image_generator::set_level_number(), affine_image_generator::set_original_image(), and affine_image_generator::set_patch_size().
Referenced by acquire_model(), CalibModel::buildCached(), and main().
void planar_object_recognizer::use_bins_when_creating_model_points (void) [inline]
Activate bins when detecting model points (Default).
Definition at line 75 of file planar_object_recognizer.h.
References use_bins_for_model_points.
void planar_object_recognizer::dont_use_bins_when_creating_model_points (void) [inline]
Disactivate bins when detecting model points.
Definition at line 77 of file planar_object_recognizer.h.
References use_bins_for_model_points.
Referenced by default_settings().
void planar_object_recognizer::use_bins_when_detecting_input_image_points (void) [inline]
Activate bins when detecting input image points (Default).
Definition at line 80 of file planar_object_recognizer.h.
References use_bins_for_input_image.
void planar_object_recognizer::dont_use_bins_when_detecting_input_image_points (void) [inline]
Disactivate bins when detecting model points.
Definition at line 82 of file planar_object_recognizer.h.
References use_bins_for_input_image.
Referenced by default_settings().
void planar_object_recognizer::set_noise_level (int noise_level)
Default = 20.
Definition at line 120 of file planar_object_recognizer.cpp.
References new_images_generator, and affine_image_generator::set_noise_level().
void planar_object_recognizer::set_use_random_background (bool use_random_background)
Default = false;.
Definition at line 115 of file planar_object_recognizer.cpp.
References new_images_generator, and affine_image_generator::set_use_random_background().
void planar_object_recognizer::set_range_variation_for_theta (float min_theta, float max_theta)
Global rotation. Default = [0 : 2Pi].
Definition at line 90 of file planar_object_recognizer.cpp.
References new_images_generator, and affine_image_generator::set_range_variation_for_theta().
void planar_object_recognizer::set_range_variation_for_phi (float min_phi, float max_phi)
Skew. Default = [0 : Pi].
Definition at line 95 of file planar_object_recognizer.cpp.
References new_images_generator, and affine_image_generator::set_range_variation_for_phi().
void planar_object_recognizer::independent_scaling (float min_lambda1, float max_lambda1, float min_lambda2, float max_lambda2)
Default method. Between 0.5 : 1.5 for both.
Definition at line 100 of file planar_object_recognizer.cpp.
References affine_image_generator::independent_scaling(), and new_images_generator.
void planar_object_recognizer::constrained_scaling (float min_lambda1, float max_lambda1, float min_lambda2, float max_lambda2, float min_l1_l2, float max_l1_l2)
Constrained scaling. Adds a constraint on the range of the product of l1 and l2.
Definition at line 106 of file planar_object_recognizer.cpp.
References affine_image_generator::constrained_scaling(), and new_images_generator.
void planar_object_recognizer::use_orientation_correction (void)
Default method.
Definition at line 80 of file planar_object_recognizer.cpp.
References new_images_generator, and affine_image_generator::set_use_orientation_correction().
void planar_object_recognizer::dont_use_orientation_correction (void)
Definition at line 85 of file planar_object_recognizer.cpp.
References new_images_generator, and affine_image_generator::set_use_orientation_correction().
void planar_object_recognizer::set_max_depth (int p_max_depth) [inline]
Default = 10.
Definition at line 107 of file planar_object_recognizer.h.
References max_depth.
Referenced by default_settings().
void planar_object_recognizer::set_sample_number_for_refining (int sample_number) [inline]
Sample number for the refine step (default = 1000):.
Definition at line 110 of file planar_object_recognizer.h.
References sample_number_for_refining.
void planar_object_recognizer::learn (int max_point_number_on_model, int patch_size, int yape_radius, int tree_number, int nbLev = 5, LEARNPROGRESSION LearnProgress = 0)
Create the point recognizer (see forest field).
Definition at line 335 of file planar_object_recognizer.cpp.
References image_class_example::alloc(), image_classification_forest::create_trees_at_random(), detect_most_stable_model_points(), detected_point_views, forest, hard_max_detected_pts, match_probabilities, max_depth, min_view_rate, model_point_number, new_images_generator, affine_image_generator::original_image, point_detector, image_classification_forest::refine(), sample_number_for_refining, save_image_of_model_points(), yape::set_radius(), yape::set_use_bins(), image_classification_forest::test(), use_bins_for_model_points, and views_number.
Referenced by build(), and build_with_cache().
void planar_object_recognizer::save (string directory_name)
Save data in the given directory. The directory must exist.
Examples:
singlecalib.cpp.
Definition at line 364 of file planar_object_recognizer.cpp.
References forest, yape::get_radius(), affine_image_generator::level_number, mcvSaveImage(), model_point_number, model_points, new_images_generator, affine_image_generator::original_image, point_detector, image_classification_forest::save(), affine_image_generator::u_corner1, affine_image_generator::u_corner2, affine_image_generator::u_corner3, affine_image_generator::u_corner4, affine_image_generator::v_corner1, affine_image_generator::v_corner2, affine_image_generator::v_corner3, and affine_image_generator::v_corner4.
Referenced by acquire_model(), build_with_cache(), CalibModel::buildCached(), and main().
bool planar_object_recognizer::load (string directory_name)
load data from a given directory.
Returns:
true on success, false on failure.
Definition at line 212 of file planar_object_recognizer.cpp.
References image_class_example::alloc(), object_keypoint::class_index, detected_point_views, forest, hard_max_detected_pts, image_classifier::image_width, initialize(), image_classification_forest::load(), object_keypoint::M, match_probabilities, mcvLoadImage(), model_point_number, model_points, new_images_generator, affine_image_generator::original_image, point_detector, object_keypoint::scale, affine_image_generator::set_gaussian_smoothing_kernel_size(), affine_image_generator::set_level_number(), affine_image_generator::set_object_keypoints(), affine_image_generator::set_original_image(), and yape::set_radius().
Referenced by build_with_cache(), and planar_object_recognizer().
bool planar_object_recognizer::detect (IplImage * input_image)
Detect the object in the given input image.
Returns true if the object is detected. If the object is detected, put the detected corners in the fieds detected_u_corner1, detected_v_corner1 ...
Calls successively the functions:
detect_points
preprocess_points
match_points
estimate_affine_transformation
estimate_homographic_transformation_nonlinear_method
Examples:
augment3d.cpp, filedetect.cpp, fullcalib.cpp, and singlecalib.cpp.
Definition at line 478 of file planar_object_recognizer.cpp.
References affine_motion, detect_points(), detected_u_corner1, detected_u_corner2, detected_u_corner3, detected_u_corner4, detected_v_corner1, detected_v_corner2, detected_v_corner3, detected_v_corner4, estimate_affine_transformation(), estimate_homographic_transformation_nonlinear_method(), H, match_points(), new_images_generator, object_is_detected, preprocess_points(), homography::transform_point(), affinity::transform_point(), affine_image_generator::u_corner1, affine_image_generator::u_corner2, affine_image_generator::u_corner3, affine_image_generator::u_corner4, affine_image_generator::v_corner1, affine_image_generator::v_corner2, affine_image_generator::v_corner3, and affine_image_generator::v_corner4.
Referenced by MultiGrab::Cam::detect(), geometric_calibration(), main(), and photometric_calibration().
void planar_object_recognizer::set_max_detected_pts (int max)
set the maximum number of points we want to detect
Definition at line 74 of file planar_object_recognizer.cpp.
References hard_max_detected_pts, and max_detected_pts.
void planar_object_recognizer::detect_points (IplImage * input_image)
Definition at line 405 of file planar_object_recognizer.cpp.
References check_target_size(), detected_point_number, detected_points, object_view::image, max_detected_pts, object_input_view, point_detector, pyr_yape::pyramidBlurDetect(), yape::set_tau(), yape::set_use_bins(), and use_bins_for_input_image.
Referenced by detect().
void planar_object_recognizer::preprocess_points (void)
Definition at line 416 of file planar_object_recognizer.cpp.
References object_view::comp_gradient(), detected_point_number, detected_point_views, detected_points, forest, image, image_classifier::image_width, mcvSaveImage(), new_images_generator, object_input_view, image_class_example::point2d, affine_image_generator::preprocess_point_view(), image_class_example::preprocessed, keypoint::scale, keypoint::u, and keypoint::v.
Referenced by detect().
void planar_object_recognizer::match_points (bool fill_match_struct = true)
Definition at line 439 of file planar_object_recognizer.cpp.
References detected_point_number, detected_point_views, forest, image, image_object_point_match::image_point, image_classifier::image_width, match_number, match_probabilities, matches, model_point_number, model_points, image_object_point_match::object_point, image_class_example::point2d, image_classification_forest::posterior_probabilities(), keypoint::scale, image_object_point_match::score, keypoint::u, and keypoint::v.
Referenced by detect().
bool planar_object_recognizer::estimate_affine_transformation (void)
Definition at line 615 of file planar_object_recognizer.cpp.
References affine_motion, compute_support_for_affine_transformation(), PyrImage::convCoordf(), affinity::estimate(), image_object_point_match::image_point, object_keypoint::M, matches, max_ransac_iterations, image_object_point_match::object_point, ransac_stop_support, keypoint::scale, object_keypoint::scale, three_random_correspondences(), keypoint::u, and keypoint::v.
Referenced by detect().
bool planar_object_recognizer::estimate_homographic_transformation_linear_method (void)
Definition at line 680 of file planar_object_recognizer.cpp.
References homography::add_match(), PyrImage::convCoordf(), homography::estimate(), H, image_object_point_match::image_point, object_keypoint::M, match_number, matches, object_is_detected, image_object_point_match::object_point, keypoint::scale, object_keypoint::scale, homography::set_match_number(), keypoint::u, and keypoint::v.
bool planar_object_recognizer::estimate_homographic_transformation_nonlinear_method (void)
Definition at line 743 of file planar_object_recognizer.cpp.
References ls_minimizer2::add_observation_2data_2measures(), affine_motion, PyrImage::convCoordf(), affinity::cvmGet(), homography::cvmSet(), H, homography_error(), homography_estimator, image_object_point_match::image_point, image_object_point_match::inlier, match_number, matches, ls_minimizer2::minimize_using_levenberg_marquardt_from(), non_linear_refine_threshold, object_is_detected, image_object_point_match::object_point, ls_minimizer2::reset_observations(), keypoint::scale, object_keypoint::scale, ls_minimizer2::set_verbose_level(), ls_minimizer2::state, and homography::transform_point().
Referenced by detect().
IplImage * planar_object_recognizer::create_result_image (IplImage * input_image, bool p_draw_points, bool p_draw_matches, bool p_draw_object, bool p_draw_model_image, int line_width = 2)
For visualization.
Examples:
filedetect.cpp.
Definition at line 1058 of file planar_object_recognizer.cpp.
References concat_model_and_input_images(), draw_matches(), draw_model(), draw_points(), model_and_input_images, and object_is_detected.
Referenced by main().
void planar_object_recognizer::debug_model_point (int p_index_of_model_point_to_debug) [inline]
For debugging: save generated patches for a particular point in dir patches, before and after orientation correction.
Definition at line 192 of file planar_object_recognizer.h.
References index_of_model_point_to_debug.
void planar_object_recognizer::save_one_image_per_match (IplImage * input_image, const char * matches_dir)
For debugging: save one image per match in dir matches.
Definition at line 1230 of file planar_object_recognizer.cpp.
References concat_model_and_input_images(), PyrImage::convCoordf(), cvPoint(), forest, image_object_point_match::image_point, image_classifier::image_width, image_object_point_match::inlier, object_keypoint::M, match_number, matches, mcvSaveImage(), model_and_input_images, image_object_point_match::object_point, object_keypoint::scale, keypoint::u, u_input_image, keypoint::v, and v_input_image.
void planar_object_recognizer::save_one_image_per_match_model_to_input (IplImage * input_image, const char * matches_dir)
Definition at line 1168 of file planar_object_recognizer.cpp.
References concat_model_and_input_images(), PyrImage::convCoordf(), cvPoint(), detected_point_number, detected_point_views, forest, image, image_classifier::image_width, object_keypoint::M, match_probabilities, mcvSaveImage(), model_and_input_images, model_point_number, model_points, image_class_example::point2d, keypoint::scale, object_keypoint::scale, keypoint::u, u_input_image, keypoint::v, and v_input_image.
void planar_object_recognizer::save_one_image_per_match_input_to_model (IplImage * input_image, const char * matches_dir)
Definition at line 1102 of file planar_object_recognizer.cpp.
References concat_model_and_input_images(), PyrImage::convCoordf(), cvPoint(), detected_point_number, detected_point_views, draw_input_image_points(), forest, image, image_classifier::image_width, object_keypoint::M, match_probabilities, mcvSaveImage(), model_and_input_images, model_point_number, model_points, image_class_example::point2d, object_keypoint::scale, keypoint::scale, keypoint::u, u_input_image, keypoint::v, and v_input_image.
void planar_object_recognizer::initialize (void)
Function called by the 2 constructors.
Definition at line 296 of file planar_object_recognizer.cpp.
References affine_motion, H, homography_estimator, affine_image_generator::level_number, model_and_input_images, new_images_generator, object_input_view, and affine_image_generator::original_image.
Referenced by build(), build_with_cache(), and load().
pair< object_keypoint, int > * planar_object_recognizer::search_for_existing_model_point (vector< pair< object_keypoint, int > > * tmp_model_points, float cu, float cv, int scale)
Definition at line 846 of file planar_object_recognizer.cpp.
References keypoint_distance_threshold.
Referenced by detect_most_stable_model_points().
void planar_object_recognizer::detect_most_stable_model_points (int max_point_number_on_model, int patch_size, int view_number, double min_view_rate, LEARNPROGRESSION LearnProgress = 0)
Definition at line 871 of file planar_object_recognizer.cpp.
References object_keypoint::class_index, cmp_tmp_model_points(), PyrImage::convCoordf(), pyr_yape::detect(), DETECT_MODEL_POINTS, affine_image_generator::generate_object_view(), affine_image_generator::generate_random_affine_transformation(), object_view::image, affine_image_generator::inside_roi(), affine_image_generator::inverse_affine_transformation(), object_keypoint::M, model_point_number, model_points, new_images_generator, affine_image_generator::original_image, point_detector, pyr_yape::pyramidBlurDetect(), save_image_of_model_points(), object_keypoint::scale, keypoint::scale, search_for_existing_model_point(), affine_image_generator::set_object_keypoints(), affine_image_generator::set_use_random_background(), affine_image_generator::smoothed_generated_object_view, keypoint::u, affine_image_generator::use_random_background, and keypoint::v.
Referenced by learn().
void planar_object_recognizer::save_image_of_model_points (int patch_size, char * filename = 0)
Definition at line 1039 of file planar_object_recognizer.cpp.
References PyrImage::convCoordf(), cvPoint(), mcvGrayToColor(), mcvRainbowColor(), mcvSaveImage(), model_point_number, model_points, new_images_generator, and affine_image_generator::original_image.
Referenced by detect_most_stable_model_points(), and learn().
int planar_object_recognizer::compute_support_for_affine_transformation (affinity * A)
Definition at line 568 of file planar_object_recognizer.cpp.
References PyrImage::convCoordf(), image_object_point_match::image_point, image_object_point_match::inlier, object_keypoint::M, match_number, matches, image_object_point_match::object_point, RANSAC_DIST_THRESHOLD, keypoint::scale, object_keypoint::scale, affinity::transform_point(), keypoint::u, keypoint::v, and valid().
Referenced by estimate_affine_transformation().
bool planar_object_recognizer::three_random_correspondences (int * n1, int * n2, int * n3)
Definition at line 534 of file planar_object_recognizer.cpp.
References match_number, match_score_threshold, matches, and rand().
Referenced by estimate_affine_transformation().
bool planar_object_recognizer::valid (affinity * A)
Definition at line 605 of file planar_object_recognizer.cpp.
References cvmGet().
Referenced by compute_support_for_affine_transformation().
void planar_object_recognizer::default_settings (void)
Some parameters for fine tuning: Called by the 2 constructors.
Definition at line 57 of file planar_object_recognizer.cpp.
References dont_use_bins_when_creating_model_points(), dont_use_bins_when_detecting_input_image_points(), index_of_model_point_to_debug, keypoint_distance_threshold, max_detected_pts, min_view_rate, sample_number_for_refining, set_max_depth(), and views_number.
Referenced by planar_object_recognizer().
void planar_object_recognizer::save_patch_before_and_after_correction (IplImage * image, int u, int v, int patch_size, image_class_example * pv, int point_index, int call_number)
The following functions are useful for visualization only:.
Definition at line 826 of file planar_object_recognizer.cpp.
References mcvGetPatch(), mcvSaveImage(), and image_class_example::preprocessed.
void planar_object_recognizer::concat_model_and_input_images (IplImage * input_image, bool p_draw_model_image = true)
Definition at line 1266 of file planar_object_recognizer.cpp.
References mcvPut(), model_and_input_images, new_images_generator, affine_image_generator::original_image, u_input_image, v_input_image, x0, and y0.
Referenced by create_result_image(), save_one_image_per_match(), save_one_image_per_match_input_to_model(), and save_one_image_per_match_model_to_input().
void planar_object_recognizer::draw_points (int line_width = 1)
Definition at line 1299 of file planar_object_recognizer.cpp.
References draw_input_image_points(), and draw_model_points().
Referenced by create_result_image().
void planar_object_recognizer::draw_model_points (int line_width = 1)
Definition at line 1305 of file planar_object_recognizer.cpp.
References PyrImage::convCoordf(), cvPoint(), forest, image_classifier::image_width, model_and_input_images, model_point_number, model_points, x0, and y0.
Referenced by draw_points().
void planar_object_recognizer::draw_input_image_points (int line_width = 1)
Definition at line 1316 of file planar_object_recognizer.cpp.
References PyrImage::convCoordf(), cvPoint(), detected_point_number, detected_points, forest, image_classifier::image_width, mcvRainbowColor(), model_and_input_images, u_input_image, and v_input_image.
Referenced by draw_points(), and save_one_image_per_match_input_to_model().
void planar_object_recognizer::draw_matches (int line_width = 2)
Definition at line 1328 of file planar_object_recognizer.cpp.
References PyrImage::convCoordf(), cvPoint(), image_object_point_match::image_point, image_object_point_match::inlier, object_keypoint::M, match_number, matches, model_and_input_images, image_object_point_match::object_point, keypoint::scale, object_keypoint::scale, keypoint::u, u_input_image, keypoint::v, and v_input_image.
Referenced by create_result_image().
void planar_object_recognizer::draw_inlier_matches (int line_width = 1)
Definition at line 1348 of file planar_object_recognizer.cpp.
References cvPoint(), image_object_point_match::image_point, image_object_point_match::inlier, object_keypoint::M, match_number, matches, model_and_input_images, image_object_point_match::object_point, keypoint::u, u_input_image, keypoint::v, and v_input_image.
void planar_object_recognizer::draw_model (void)
Definition at line 1081 of file planar_object_recognizer.cpp.
References cvPoint(), detected_u_corner1, detected_u_corner2, detected_u_corner3, detected_u_corner4, detected_v_corner1, detected_v_corner2, detected_v_corner3, detected_v_corner4, model_and_input_images, u_input_image, and v_input_image.
Referenced by create_result_image().
void planar_object_recognizer::check_target_size (IplImage * image)
Ensures that allocated resources are ready to handle an image of the given size.
Definition at line 1367 of file planar_object_recognizer.cpp.
References yape::get_radius(), object_view::image, affine_image_generator::level_number, new_images_generator, object_input_view, affine_image_generator::orientation_corrector, affine_image_generator::patch_size, point_detector, and yape::set_radius().
Referenced by detect_points().
Member Data Documentation
int planar_object_recognizer::sample_number_for_refining
Definition at line 111 of file planar_object_recognizer.h.
Referenced by default_settings(), learn(), and set_sample_number_for_refining().
object_keypoint* planar_object_recognizer::model_points
keypoints on the object.
(X, Y) = coordinates in the original image, Z = 0. usage: model_points[target][model], with 0 <= target < detected_point_number and 0 <= model < model_point_number
Definition at line 159 of file planar_object_recognizer.h.
Referenced by detect_most_stable_model_points(), draw_model_points(), load(), match_points(), planar_object_recognizer(), save(), save_image_of_model_points(), save_one_image_per_match_input_to_model(), save_one_image_per_match_model_to_input(), and ~planar_object_recognizer().
int planar_object_recognizer::model_point_number
Definition at line 160 of file planar_object_recognizer.h.
Referenced by detect_most_stable_model_points(), draw_model_points(), learn(), load(), match_points(), save(), save_image_of_model_points(), save_one_image_per_match_input_to_model(), and save_one_image_per_match_model_to_input().
keypoint* planar_object_recognizer::detected_points
Detected keypoints in the input image.
Definition at line 163 of file planar_object_recognizer.h.
Referenced by detect_points(), draw_input_image_points(), planar_object_recognizer(), preprocess_points(), and ~planar_object_recognizer().
int planar_object_recognizer::detected_point_number
Definition at line 164 of file planar_object_recognizer.h.
Referenced by detect_points(), draw_input_image_points(), match_points(), preprocess_points(), save_one_image_per_match_input_to_model(), and save_one_image_per_match_model_to_input().
image_class_example* planar_object_recognizer::detected_point_views
Definition at line 165 of file planar_object_recognizer.h.
Referenced by learn(), load(), match_points(), planar_object_recognizer(), preprocess_points(), save_one_image_per_match_input_to_model(), save_one_image_per_match_model_to_input(), and ~planar_object_recognizer().
float* planar_object_recognizer::match_probabilities[hard_max_detected_pts]
Match probabilities for each detected keypoint.
Definition at line 168 of file planar_object_recognizer.h.
Referenced by learn(), load(), match_points(), save_one_image_per_match_input_to_model(), save_one_image_per_match_model_to_input(), and ~planar_object_recognizer().
image_object_point_match planar_object_recognizer::matches[hard_max_detected_pts]
Matches between the detected keypoints, and the model keypoints.
Examples:
augment3d.cpp, fullcalib.cpp, multicam.cpp, and singlecalib.cpp.
Definition at line 170 of file planar_object_recognizer.h.
Referenced by add_detected_homography(), compute_support_for_affine_transformation(), draw_inlier_matches(), draw_matches(), estimate_affine_transformation(), estimate_homographic_transformation_linear_method(), estimate_homographic_transformation_nonlinear_method(), geom_calib_draw(), match_points(), save_one_image_per_match(), show_result(), and three_random_correspondences().
int planar_object_recognizer::match_number
Examples:
augment3d.cpp, fullcalib.cpp, multicam.cpp, and singlecalib.cpp.
Definition at line 171 of file planar_object_recognizer.h.
Referenced by add_detected_homography(), compute_support_for_affine_transformation(), draw_inlier_matches(), draw_matches(), estimate_homographic_transformation_linear_method(), estimate_homographic_transformation_nonlinear_method(), geom_calib_draw(), match_points(), save_one_image_per_match(), show_result(), and three_random_correspondences().
bool planar_object_recognizer::object_is_detected
Examples:
fullcalib.cpp, multicam.cpp, and singlecalib.cpp.
Definition at line 173 of file planar_object_recognizer.h.
Referenced by augment_scene(), create_result_image(), detect(), estimate_homographic_transformation_linear_method(), estimate_homographic_transformation_nonlinear_method(), geom_calib_draw(), photometric_calibration(), and show_result().
affinity* planar_object_recognizer::affine_motion
Definition at line 174 of file planar_object_recognizer.h.
Referenced by detect(), estimate_affine_transformation(), estimate_homographic_transformation_nonlinear_method(), initialize(), planar_object_recognizer(), and ~planar_object_recognizer().
homography* planar_object_recognizer::H
Examples:
augment3d.cpp, fullcalib.cpp, and singlecalib.cpp.
Definition at line 175 of file planar_object_recognizer.h.
Referenced by add_detected_homography(), MultiGrab::Cam::detect(), detect(), estimate_homographic_transformation_linear_method(), estimate_homographic_transformation_nonlinear_method(), initialize(), photometric_calibration(), planar_object_recognizer(), and ~planar_object_recognizer().
ls_minimizer2* planar_object_recognizer::homography_estimator
Definition at line 176 of file planar_object_recognizer.h.
Referenced by estimate_homographic_transformation_nonlinear_method(), initialize(), planar_object_recognizer(), and ~planar_object_recognizer().
float planar_object_recognizer::detected_u_corner1
Definition at line 177 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
float planar_object_recognizer::detected_v_corner1
Definition at line 177 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
float planar_object_recognizer::detected_u_corner2
Definition at line 178 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
float planar_object_recognizer::detected_v_corner2
Definition at line 178 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
float planar_object_recognizer::detected_u_corner3
Definition at line 179 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
float planar_object_recognizer::detected_v_corner3
Definition at line 179 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
float planar_object_recognizer::detected_u_corner4
Definition at line 180 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
float planar_object_recognizer::detected_v_corner4
Definition at line 180 of file planar_object_recognizer.h.
Referenced by detect(), and draw_model().
pyr_yape* planar_object_recognizer::point_detector
Definition at line 182 of file planar_object_recognizer.h.
Referenced by check_target_size(), detect_most_stable_model_points(), detect_points(), learn(), load(), planar_object_recognizer(), save(), and ~planar_object_recognizer().
affine_image_generator planar_object_recognizer::new_images_generator
Definition at line 205 of file planar_object_recognizer.h.
Referenced by build(), build_with_cache(), CalibModel::buildCached(), check_target_size(), concat_model_and_input_images(), constrained_scaling(), detect(), detect_most_stable_model_points(), dont_use_orientation_correction(), independent_scaling(), initialize(), learn(), load(), preprocess_points(), save(), save_image_of_model_points(), set_noise_level(), set_range_variation_for_phi(), set_range_variation_for_theta(), set_use_random_background(), and use_orientation_correction().
object_view* planar_object_recognizer::object_input_view
Definition at line 207 of file planar_object_recognizer.h.
Referenced by check_target_size(), detect_points(), initialize(), planar_object_recognizer(), preprocess_points(), and ~planar_object_recognizer().
image_classification_forest* planar_object_recognizer::forest
Image classifier.
Definition at line 218 of file planar_object_recognizer.h.
Referenced by draw_input_image_points(), draw_model_points(), learn(), load(), match_points(), planar_object_recognizer(), preprocess_points(), save(), save_one_image_per_match(), save_one_image_per_match_input_to_model(), save_one_image_per_match_model_to_input(), and ~planar_object_recognizer().
int planar_object_recognizer::max_detected_pts
Definition at line 225 of file planar_object_recognizer.h.
Referenced by default_settings(), detect_points(), and set_max_detected_pts().
int planar_object_recognizer::max_depth
Definition at line 226 of file planar_object_recognizer.h.
Referenced by learn(), and set_max_depth().
bool planar_object_recognizer::use_bins_for_model_points
Definition at line 231 of file planar_object_recognizer.h.
Referenced by dont_use_bins_when_creating_model_points(), learn(), and use_bins_when_creating_model_points().
bool planar_object_recognizer::use_bins_for_input_image
Definition at line 232 of file planar_object_recognizer.h.
Referenced by detect_points(), dont_use_bins_when_detecting_input_image_points(), and use_bins_when_detecting_input_image_points().
int planar_object_recognizer::index_of_model_point_to_debug
Definition at line 233 of file planar_object_recognizer.h.
Referenced by debug_model_point(), and default_settings().
int planar_object_recognizer::views_number
number of generated views for finding stable points
Examples:
filedetect.cpp.
Definition at line 236 of file planar_object_recognizer.h.
Referenced by CalibModel::buildCached(), default_settings(), learn(), and main().
double planar_object_recognizer::min_view_rate
minimum visible rate for determining stable keypoints
Examples:
filedetect.cpp.
Definition at line 239 of file planar_object_recognizer.h.
Referenced by CalibModel::buildCached(), default_settings(), learn(), and main().
double planar_object_recognizer::keypoint_distance_threshold
interest points that are closer than this distance are merged by by search_for_existing_model_point().
Definition at line 244 of file planar_object_recognizer.h.
Referenced by default_settings(), and search_for_existing_model_point().
float planar_object_recognizer::match_score_threshold
The RANSAC estimation will not take into account a match whose score is under that threshold.
Examples:
augment3d.cpp, filedetect.cpp, and singlecalib.cpp.
Definition at line 249 of file planar_object_recognizer.h.
Referenced by CalibModel::buildCached(), main(), planar_object_recognizer(), and three_random_correspondences().
float planar_object_recognizer::ransac_dist_threshold
The minimum reprojection distance that RANSAC will consider compatible.
Examples:
augment3d.cpp, filedetect.cpp, and singlecalib.cpp.
Definition at line 253 of file planar_object_recognizer.h.
Referenced by CalibModel::buildCached(), main(), and planar_object_recognizer().
float planar_object_recognizer::non_linear_refine_threshold
Distance threshold, in pixels, for non-linear refinement.
Examples:
augment3d.cpp, filedetect.cpp, and singlecalib.cpp.
Definition at line 256 of file planar_object_recognizer.h.
Referenced by CalibModel::buildCached(), estimate_homographic_transformation_nonlinear_method(), main(), and planar_object_recognizer().
int planar_object_recognizer::max_ransac_iterations
maximum iteration number for RANSAC
Examples:
augment3d.cpp, filedetect.cpp, and singlecalib.cpp.
Definition at line 259 of file planar_object_recognizer.h.
Referenced by CalibModel::buildCached(), estimate_affine_transformation(), main(), and planar_object_recognizer().
int planar_object_recognizer::ransac_stop_support
RANSAC will stop if it finds a transformation that satisfies at least ransac_stop_support matches.
Definition at line 264 of file planar_object_recognizer.h.
Referenced by estimate_affine_transformation(), and planar_object_recognizer().
IplImage* planar_object_recognizer::model_and_input_images
Definition at line 280 of file planar_object_recognizer.h.
Referenced by concat_model_and_input_images(), create_result_image(), draw_inlier_matches(), draw_input_image_points(), draw_matches(), draw_model(), draw_model_points(), initialize(), planar_object_recognizer(), save_one_image_per_match(), save_one_image_per_match_input_to_model(), and save_one_image_per_match_model_to_input().
int planar_object_recognizer::x0
Definition at line 281 of file planar_object_recognizer.h.
Referenced by concat_model_and_input_images(), and draw_model_points().
int planar_object_recognizer::y0
Definition at line 281 of file planar_object_recognizer.h.
Referenced by concat_model_and_input_images(), and draw_model_points().
int planar_object_recognizer::u_input_image
Definition at line 282 of file planar_object_recognizer.h.
Referenced by concat_model_and_input_images(), draw_inlier_matches(), draw_input_image_points(), draw_matches(), draw_model(), save_one_image_per_match(), save_one_image_per_match_input_to_model(), and save_one_image_per_match_model_to_input().
int planar_object_recognizer::v_input_image
Definition at line 282 of file planar_object_recognizer.h.
Referenced by concat_model_and_input_images(), draw_inlier_matches(), draw_input_image_points(), draw_matches(), draw_model(), save_one_image_per_match(), save_one_image_per_match_input_to_model(), and save_one_image_per_match_model_to_input().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/viewsets/planar_object_recognizer.h
/home/julian/devel/artvertiser/garfeild/viewsets/planar_object_recognizer.cpp