bazar: IplTexture Class Reference
IplTexture Class Reference
[Photometric Calibration]
#include <ipltexture.h>
Public Member Functions
IplTexture (IplImage *image=0, bool cache=true, bool smooth=true)
virtual ~IplTexture ()
void genTexture ()
Only call genTexture from a valid OpenGL context !
void loadTexture ()
void disableTexture ()
void update ()
void setImage (IplImage *image)
IplImage * getImage ()
IplImage * getIm ()
const IplImage * getIm () const
void freeImage ()
double u (double x)
Get the U texel coordinates from pixel coordinate x.
double v (double y)
Get the V texel coordinates from pixel coordinate y (axis pointing down).
void regen ()
force texture regeneration.
void addRef ()
Add a reference to the reference counter.
void unref ()
void clearWithoutDelete ()
Detailed Description
Represent a texture in video memory, with optional caching.
Honours many IplImage fields like nChannels, depth, align, and origin.
Examples:
multigl.cpp.
Definition at line 44 of file ipltexture.h.
Constructor & Destructor Documentation
IplTexture::IplTexture (IplImage * image = 0, bool cache = true, bool smooth = true) [inline]
Definition at line 47 of file ipltexture.h.
IplTexture::~IplTexture () [virtual]
Definition at line 4 of file ipltexture.cpp.
Member Function Documentation
void IplTexture::genTexture ()
Only call genTexture from a valid OpenGL context !
Definition at line 9 of file ipltexture.cpp.
Referenced by loadTexture().
void IplTexture::loadTexture ()
Examples:
multigl.cpp.
Definition at line 43 of file ipltexture.cpp.
References format, and genTexture().
Referenced by drawBackground(), LightMap::enableShader(), and photo_draw().
void IplTexture::disableTexture ()
Examples:
multigl.cpp.
Definition at line 103 of file ipltexture.cpp.
Referenced by LightMap::disableShader(), drawBackground(), and photo_draw().
void IplTexture::update () [inline]
Definition at line 57 of file ipltexture.h.
Referenced by regen(), and setImage().
void IplTexture::setImage (IplImage * image)
Examples:
multigl.cpp.
Definition at line 117 of file ipltexture.cpp.
References update().
Referenced by geom_calib_idle(), LightMap::init(), LightMap::LightMap(), photo_draw(), and photo_idle().
IplImage* IplTexture::getImage () [inline]
Definition at line 59 of file ipltexture.h.
IplImage* IplTexture::getIm () [inline]
Examples:
fullcalib.cpp, and multigl.cpp.
Definition at line 60 of file ipltexture.h.
Referenced by LightMap::addNormalLightMap(), LightMap::computeLightParams(), drawBackground(), LightMap::init(), LightMap::LightMap(), photo_draw(), photometric_calibration(), LightMap::readMap(), LightMap::saveImage(), and LightMap::~LightMap().
const IplImage* IplTexture::getIm () const [inline]
Definition at line 61 of file ipltexture.h.
void IplTexture::freeImage () [inline]
Definition at line 62 of file ipltexture.h.
double IplTexture::u (double x) [inline]
Get the U texel coordinates from pixel coordinate x.
Examples:
multigl.cpp.
Definition at line 65 of file ipltexture.h.
Referenced by drawBackground().
double IplTexture::v (double y) [inline]
Get the V texel coordinates from pixel coordinate y (axis pointing down).
Examples:
multigl.cpp.
Definition at line 68 of file ipltexture.h.
Referenced by drawBackground().
void IplTexture::regen ()
force texture regeneration.
Definition at line 123 of file ipltexture.cpp.
References update().
void IplTexture::addRef () [inline]
Add a reference to the reference counter.
Definition at line 74 of file ipltexture.h.
void IplTexture::unref ()
Removes a reference to the reference counter, and delete the texture if it reaches 0.
Definition at line 110 of file ipltexture.cpp.
void IplTexture::clearWithoutDelete () [inline]
Definition at line 81 of file ipltexture.h.
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/lightcalib/ipltexture.h
/home/julian/devel/artvertiser/garfeild/lightcalib/ipltexture.cpp