bazar: PerspectiveCamera Class Reference
PerspectiveCamera Class Reference
#include <camera.h>
Public Member Functions
PerspectiveCamera ()
void worldToImage (const double p[3], double uvw[3]) const
void worldToImage (const Vec3 &p, Vec3 &uvw) const
void worldToEye (const Vec3 &src, Vec3 &dst) const
void worldToEye (const double src[3], double dst[3]) const
void eyeToWorld (const Vec3 &uvw, Vec3 &w) const
void imageToWorld (double u, double v, Vec3 &w, double z=0) const
void setGlModelView () const
void setByTarget (const Vec3 pos, const Vec3 target, double roll)
void loadTdir (const double tdir[3][4], int w, int h)
bool loadTdir (const char *tdir, int w, int h)
bool loadTdir (const char *tdir)
void clearExternalParams ()
void translate (double dx, double dy, double dz)
translate the camera relative to eye coordinates (z means "move forward").
void setWorldToEyeMat (const Mat3x4 &m)
const Mat3x4 & getWorldToEyeMat () const
const Mat3x4 & getEyeToWorldMat () const
const Mat3x4 & getWorldToImageMat () const
void cmpWorldToImageMat ()
bool saveTdir (const char *file)
Save the camera in a tdir file. Returns true on success, false on failure.
Protected Attributes
Mat3x4 worldToEyeMat
Mat3x4 eyeToWorldMat
Mat3x4 worldToImageMat
Detailed Description
Perspective camera: a projection located in space.
Examples:
multigl.cpp.
Definition at line 56 of file camera.h.
Constructor & Destructor Documentation
PerspectiveCamera::PerspectiveCamera ()
Definition at line 191 of file camera.cpp.
References clearExternalParams(), PerspectiveProjection::f, and translate().
Member Function Documentation
void PerspectiveCamera::worldToImage (const double p[3], double uvw[3]) const
Definition at line 204 of file camera.cpp.
void PerspectiveCamera::worldToImage (const Vec3 & p, Vec3 & uvw) const
Definition at line 197 of file camera.cpp.
References Vec3::setMul(), Vec3::v, and worldToImageMat.
void PerspectiveCamera::worldToEye (const Vec3 & src, Vec3 & dst) const
Definition at line 209 of file camera.cpp.
References Vec3::setMul(), and worldToEyeMat.
void PerspectiveCamera::worldToEye (const double src[3], double dst[3]) const
Definition at line 214 of file camera.cpp.
References worldToEyeMat.
void PerspectiveCamera::eyeToWorld (const Vec3 & uvw, Vec3 & w) const
Definition at line 496 of file camera.cpp.
References eyeToWorldMat, and Vec3::setMul().
Referenced by imageToWorld().
void PerspectiveCamera::imageToWorld (double u, double v, Vec3 & w, double z = 0) const
Definition at line 501 of file camera.cpp.
References eyeToWorld(), PerspectiveProjection::imageToEye(), and Vec3::v.
void PerspectiveCamera::setGlModelView () const
Examples:
multigl.cpp.
Definition at line 219 of file camera.cpp.
References Mat3x4::m, and worldToEyeMat.
Referenced by photo_draw().
void PerspectiveCamera::setByTarget (const Vec3 pos, const Vec3 target, double roll)
Definition at line 238 of file camera.cpp.
References cmpWorldToImageMat(), Mat3x4::m, Vec3::normalize(), Vec3::setCross(), Vec3::setSub(), and worldToEyeMat.
void PerspectiveCamera::loadTdir (const double _tdir[3][4], int w, int h)
This function separate intrinsic and extrinsic parameters from a single projection matrix. The resulting rotation matrix (worldToEyeMat) determinant is always positive.
Examples:
multigl.cpp.
Definition at line 295 of file camera.cpp.
References PerspectiveProjection::cmpEyeToImageMat(), PerspectiveProjection::cx, PerspectiveProjection::cy, Mat3x4::det(), eyeToWorldMat, PerspectiveProjection::f, PerspectiveProjection::g, get3x3MulWithTransposed(), PerspectiveProjection::height, Mat3x4::m, PerspectiveProjection::s, Mat3x4::setInverseByTranspose(), PerspectiveProjection::width, worldToEyeMat, and worldToImageMat.
Referenced by loadTdir(), and photo_draw().
bool PerspectiveCamera::loadTdir (const char * tdirFile, int w, int h)
Load external and internal parameters from a tdir file. The w and h specify the size of the projection rectangle.
Returns:
true on success, false on failure.
Definition at line 356 of file camera.cpp.
References PerspectiveProjection::distortion, PerspectiveProjection::f, PerspectiveProjection::farPlane, loadTdir(), PerspectiveProjection::nearPlane, and PerspectiveProjection::setPlanes().
bool PerspectiveCamera::loadTdir (const char * tdirFile)
Load external and internal parameters from a tdir file, estimating image width and height.
THE WIDTH AND HEIGHT ESTIMATION MIGHT BE WRONG!
Returns:
true on success, false on failure.
Definition at line 450 of file camera.cpp.
References PerspectiveProjection::cx, PerspectiveProjection::cy, diagDiff(), GuessMode::h, PerspectiveProjection::height, loadTdir(), GuessMode::w, and PerspectiveProjection::width.
void PerspectiveCamera::clearExternalParams ()
Definition at line 484 of file camera.cpp.
References cmpWorldToImageMat(), Mat3x4::setIdentity(), and worldToEyeMat.
Referenced by PerspectiveCamera().
void PerspectiveCamera::translate (double dx, double dy, double dz)
translate the camera relative to eye coordinates (z means "move forward").
Definition at line 508 of file camera.cpp.
References cmpWorldToImageMat(), Mat3x4::m, and worldToEyeMat.
Referenced by PerspectiveCamera().
void PerspectiveCamera::setWorldToEyeMat (const Mat3x4 & m)
Examples:
multigl.cpp.
Definition at line 516 of file camera.cpp.
References cmpWorldToImageMat(), and worldToEyeMat.
Referenced by photo_draw().
const Mat3x4& PerspectiveCamera::getWorldToEyeMat () const [inline]
Examples:
multigl.cpp.
Definition at line 77 of file camera.h.
References worldToEyeMat.
Referenced by operator<<(), and photo_draw().
const Mat3x4& PerspectiveCamera::getEyeToWorldMat () const [inline]
Definition at line 78 of file camera.h.
References eyeToWorldMat.
const Mat3x4& PerspectiveCamera::getWorldToImageMat () const [inline]
Definition at line 79 of file camera.h.
References worldToImageMat.
void PerspectiveCamera::cmpWorldToImageMat ()
Definition at line 490 of file camera.cpp.
References PerspectiveProjection::eyeToImageMat, eyeToWorldMat, Mat3x4::setInverseByTranspose(), Mat3x4::setMul(), worldToEyeMat, and worldToImageMat.
Referenced by clearExternalParams(), setByTarget(), setWorldToEyeMat(), and translate().
bool PerspectiveCamera::saveTdir (const char * file)
Save the camera in a tdir file. Returns true on success, false on failure.
Definition at line 522 of file camera.cpp.
References PerspectiveProjection::distortion, PerspectiveProjection::f, PerspectiveProjection::farPlane, PerspectiveProjection::height, Mat3x4::m, PerspectiveProjection::nearPlane, PerspectiveProjection::width, and worldToImageMat.
Member Data Documentation
Mat3x4 PerspectiveCamera::worldToEyeMat [protected]
Definition at line 88 of file camera.h.
Referenced by clearExternalParams(), cmpWorldToImageMat(), getWorldToEyeMat(), loadTdir(), setByTarget(), setGlModelView(), setWorldToEyeMat(), translate(), and worldToEye().
Mat3x4 PerspectiveCamera::eyeToWorldMat [protected]
Definition at line 89 of file camera.h.
Referenced by cmpWorldToImageMat(), eyeToWorld(), getEyeToWorldMat(), and loadTdir().
Mat3x4 PerspectiveCamera::worldToImageMat [protected]
Definition at line 90 of file camera.h.
Referenced by cmpWorldToImageMat(), getWorldToImageMat(), loadTdir(), saveTdir(), and worldToImage().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/calib/camera.h
/home/julian/devel/artvertiser/garfeild/calib/camera.cpp