bazar: object_view Class Reference
object_view Class Reference
[Viewsets]
#include <object_view.h>
Public Member Functions
object_view (PyrImage *image)
object_view (int width, int height, int nbLev)
~object_view ()
void build_from_image_0 (int kernelSize=3)
void build (IplImage *im, int kernelSize=-1)
void comp_gradient ()
Public Attributes
PyrImage image
PyrImage gradX
PyrImage gradY
float affine_projection [6]
int u0
int v0
float alpha
float scale
Detailed Description
an object view contains 3 pyramids for image and gradient
Definition at line 34 of file object_view.h.
Constructor & Destructor Documentation
object_view::object_view (PyrImage * image)
Definition at line 28 of file object_view.cpp.
object_view::object_view (int width, int height, int nbLev)
Definition at line 36 of file object_view.cpp.
object_view::~object_view ()
Definition at line 75 of file object_view.cpp.
Member Function Documentation
void object_view::build_from_image_0 (int kernelSize = 3)
Definition at line 43 of file object_view.cpp.
References PyrImage::build(), comp_gradient(), image, and PyrImage::smoothLevel0().
void object_view::build (IplImage * im, int kernelSize = -1)
Definition at line 55 of file object_view.cpp.
References PyrImage::build(), comp_gradient(), and image.
Referenced by affine_image_generator::generate_object_view().
void object_view::comp_gradient ()
Definition at line 67 of file object_view.cpp.
References gradX, gradY, image, and PyrImage::nbLev.
Referenced by build(), build_from_image_0(), and planar_object_recognizer::preprocess_points().
Member Data Documentation
PyrImage object_view::image
Definition at line 50 of file object_view.h.
Referenced by build(), build_from_image_0(), planar_object_recognizer::check_target_size(), comp_gradient(), planar_object_recognizer::detect_most_stable_model_points(), planar_object_recognizer::detect_points(), affine_image_generator::generate_random_examples(), and affine_image_generator::preprocess_point_view().
PyrImage object_view::gradX
Definition at line 51 of file object_view.h.
Referenced by comp_gradient(), and affine_image_generator::preprocess_point_view().
PyrImage object_view::gradY
Definition at line 52 of file object_view.h.
Referenced by comp_gradient(), and affine_image_generator::preprocess_point_view().
float object_view::affine_projection[6]
Definition at line 54 of file object_view.h.
int object_view::u0
Definition at line 55 of file object_view.h.
int object_view::v0
Definition at line 55 of file object_view.h.
float object_view::alpha
Definition at line 56 of file object_view.h.
float object_view::scale
Definition at line 56 of file object_view.h.
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/viewsets/object_view.h
/home/julian/devel/artvertiser/garfeild/viewsets/object_view.cpp