bazar: pyr_yape Class Reference
pyr_yape Class Reference
[Feature points detection]
Pyramidal YAPE (Feature point extractor).
#include <yape.h>
Public Member Functions
pyr_yape (int w, int h, int nbLev)
virtual ~pyr_yape ()
int pyramidBlurDetect (IplImage *im, keypoint *points, int max_point_number, PyrImage *caller_pim=0)
Blur the given image, build a pyramid and call detect().
int detect (IplImage *im, keypoint *points, int max_point_number)
Call pyramidBlurDetect():.
int detect (PyrImage *image, keypoint *points, int max_point_number)
Pyramidal feature point detection.
void save_image_of_detected_points (char *name, IplImage *image, keypoint *points, int points_nb)
Save a color image with the detected points on the original image. Useful for visualisation...
void stat_points (keypoint *points, int nb_pts)
compute and print on stdout a keypoint scale histogram.
void select_level (int l)
Public Attributes
PyrImage * internal_pim
PyrImage * pscores
dir_table * pDirs [12]
int * pDirs_nb [12]
bool equalize
Limit the maximum number of detected keypoint per level.
Detailed Description
Pyramidal YAPE (Feature point extractor).
Improve Yape to work with multi-scale pyramids (PyrImage).
Definition at line 200 of file yape.h.
Constructor & Destructor Documentation
pyr_yape::pyr_yape (int w, int h, int nbLev)
Parameters:
w width passed to Yape constructor
h height passed to Yape constructor
nbLev pyramid depth
Definition at line 823 of file yape.cpp.
References yape::Dirs, yape::Dirs_nb, equalize, internal_pim, pDirs, pDirs_nb, yape::precompute_directions(), pscores, yape::scores, and yape_max_radius.
pyr_yape::~pyr_yape () [virtual]
Definition at line 842 of file yape.cpp.
References yape::Dirs, yape::Dirs_nb, internal_pim, PyrImage::nbLev, pDirs, pDirs_nb, pscores, and yape::scores.
Member Function Documentation
int pyr_yape::pyramidBlurDetect (IplImage * im, keypoint * points, int max_point_number, PyrImage * caller_pim = 0)
Blur the given image, build a pyramid and call detect().
This method does the following: 1) Apply a Gaussian blur filter on the provided image, putting the result in the pyramid lowest level. 2) Build the pyramid 3) call detect() on it.
If no pyramid is given by the caller, a temporary pyramid image is created and recycled for future calls.
Parameters:
im the input image. Must be 1 channel (gray levels).
points an array to store keypoints.
max_point_number the size of this array.
caller_pim the pyramid to work on, or 0 for an internal pyramid.
Definition at line 903 of file yape.cpp.
References PyrImage::build(), detect(), PyrImage::images, internal_pim, PyrImage::nbLev, pscores, and yape::radius.
Referenced by detect(), planar_object_recognizer::detect_most_stable_model_points(), and planar_object_recognizer::detect_points().
int pyr_yape::detect (IplImage * im, keypoint * points, int max_point_number) [inline]
Call pyramidBlurDetect():.
Definition at line 209 of file yape.h.
References pyramidBlurDetect().
Referenced by planar_object_recognizer::detect_most_stable_model_points(), and pyramidBlurDetect().
int pyr_yape::detect (PyrImage * image, keypoint * points, int max_point_number)
Pyramidal feature point detection.
Detect features on the pyramid, filling the scale field of keypoints with the pyramid level.
Returns:
the detected keypoint number.
Definition at line 867 of file yape.cpp.
References yape::get_local_maxima(), PyrImage::images, PyrImage::nbLev, yape::pick_best_points(), yape::radius, yape::raw_detect(), yape::reserve_tmp_arrays(), select_level(), and yape::subpix_refine().
void pyr_yape::save_image_of_detected_points (char * name, IplImage * image, keypoint * points, int points_nb)
Save a color image with the detected points on the original image. Useful for visualisation...
Reimplemented from yape.
Definition at line 939 of file yape.cpp.
References PyrImage::convCoord(), PyrImage::convCoordf(), mcvCircle(), mcvGrayToColor(), mcvRainbowColor(), mcvSaveImage(), and yape::radius.
void pyr_yape::stat_points (keypoint * points, int nb_pts)
compute and print on stdout a keypoint scale histogram.
Definition at line 951 of file yape.cpp.
References PyrImage::nbLev, pscores, and keypoint::scale.
void pyr_yape::select_level (int l)
Definition at line 857 of file yape.cpp.
References yape::Dirs, yape::Dirs_nb, PyrImage::images, pDirs, pDirs_nb, pscores, and yape::scores.
Referenced by detect().
Member Data Documentation
PyrImage* pyr_yape::internal_pim
Definition at line 224 of file yape.h.
Referenced by pyr_yape(), pyramidBlurDetect(), and ~pyr_yape().
PyrImage* pyr_yape::pscores
Definition at line 225 of file yape.h.
Referenced by pyr_yape(), pyramidBlurDetect(), select_level(), stat_points(), and ~pyr_yape().
dir_table* pyr_yape::pDirs[12]
Definition at line 226 of file yape.h.
Referenced by pyr_yape(), select_level(), and ~pyr_yape().
int* pyr_yape::pDirs_nb[12]
Definition at line 227 of file yape.h.
Referenced by pyr_yape(), select_level(), and ~pyr_yape().
bool pyr_yape::equalize
Limit the maximum number of detected keypoint per level.
Definition at line 230 of file yape.h.
Referenced by pyr_yape().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/keypoints/yape.h
/home/julian/devel/artvertiser/garfeild/keypoints/yape.cpp