bazar: MultiGrab Class Reference
MultiGrab Class Reference
#include <multigrab.h>
Public Member Functions
MultiGrab (const char *modelfile="model.bmp")
int init (bool cacheTraining, char *argv)
void grabFrames ()
void allocLightCollector ()
MultiGrab (const char *modelfile="model.bmp")
int init (bool cacheTraining)
void grabFrames ()
void allocLightCollector ()
Public Attributes
CalibModel model
std::vector< Cam * > cams
Classes
struct Cam
Detailed Description
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 6 of file multigrab.h.
Constructor & Destructor Documentation
MultiGrab::MultiGrab (const char * modelfile = "model.bmp") [inline]
Definition at line 11 of file multigrab.h.
MultiGrab::MultiGrab (const char * modelfile = "model.bmp") [inline]
Definition at line 11 of file multigrab.h.
Member Function Documentation
int MultiGrab::init (bool cacheTraining, char * argv)
TODO mem to mem copy from cams[0]
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 3 of file multigrab.cpp.
References CalibModel::buildCached(), cams, and model.
Referenced by init(), and main().
void MultiGrab::grabFrames ()
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 46 of file multigrab.cpp.
References cams.
Referenced by geom_calib_idle(), geometric_calibration(), photo_idle(), and photometric_calibration().
void MultiGrab::allocLightCollector ()
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 54 of file multigrab.cpp.
References cams, CalibModel::map, model, and LightMap::reflc.
Referenced by main(), and photo_start().
int MultiGrab::init (bool cacheTraining)
TODO mem to mem copy from cams[0]
Definition at line 3 of file multigrab.cpp.
References CalibModel::buildCached(), cams, and model.
void MultiGrab::grabFrames ()
void MultiGrab::allocLightCollector ()
Member Data Documentation
CalibModel MultiGrab::model
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 9 of file multigrab.h.
Referenced by allocLightCollector(), geom_calib_end(), geom_calib_start(), geometric_calibration(), init(), photo_draw(), photo_idle(), photo_start(), and photometric_calibration().
std::vector< Cam * > MultiGrab::cams
Examples:
multicam.cpp, and multigl.cpp.
Definition at line 40 of file multigrab.h.
Referenced by allocLightCollector(), geom_calib_draw(), geom_calib_idle(), geom_calib_start(), geometric_calibration(), grabFrames(), init(), photo_draw(), photo_idle(), and photometric_calibration().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/samples/artvertiser/multigrab.h
/home/julian/devel/artvertiser/samples/multicam/multigrab.h
/home/julian/devel/artvertiser/samples/artvertiser/multigrab.cpp
/home/julian/devel/artvertiser/samples/multicam/multigrab.cpp