bazar: image_classification_forest Class Reference
image_classification_forest Class Reference
[Viewsets]
Set of classifier trees.
#include <image_classification_forest.h>
Public Member Functions
image_classification_forest (LEARNPROGRESSION LearnProgress=0)
image_classification_forest (int image_width, int image_height, int class_number, int max_depth, int trees_number, LEARNPROGRESSION LearnProgress=0)
~image_classification_forest ()
void set_saving_directory_name (string directory_name)
void create_trees_at_random (void)
virtual void refine (example_generator *vg, int call_number)
void restore_occurances ()
void reset_class_occurances (int class_index)
virtual void test (example_generator *vg, int call_number)
int recognize (image_class_example *pv, float *confidence=0, int tree_number=-1)
virtual float * posterior_probabilities (image_class_example *pv, int tree_number=-1)
virtual void posterior_probabilities (image_class_example *pv, float *pp, int tree_number=-1)
void change_class_number_and_reset_probabilities (int new_class_number)
bool load (string directory_name)
bool save (string directory_name)
bool is_ok ()
Public Attributes
float * thresholds
float * misclassification_rates
vector
< image_classification_tree * > trees
int tree_number
int max_depth
float * weights
string directory_name
Detailed Description
Set of classifier trees.
Definition at line 32 of file image_classification_forest.h.
Constructor & Destructor Documentation
image_classification_forest::image_classification_forest (LEARNPROGRESSION LearnProgress = 0)
Definition at line 28 of file image_classification_forest.cpp.
References weights.
image_classification_forest::image_classification_forest (int image_width, int image_height, int class_number, int max_depth, int trees_number, LEARNPROGRESSION LearnProgress = 0)
Definition at line 34 of file image_classification_forest.cpp.
References image_classifier::class_number, max_depth, misclassification_rates, thresholds, tree_number, and weights.
image_classification_forest::~image_classification_forest ()
Definition at line 135 of file image_classification_forest.cpp.
References misclassification_rates, thresholds, trees, and weights.
Member Function Documentation
void image_classification_forest::set_saving_directory_name (string directory_name)
Definition at line 152 of file image_classification_forest.cpp.
References directory_name.
void image_classification_forest::create_trees_at_random (void)
Definition at line 157 of file image_classification_forest.cpp.
References BUILDING_TREE, image_classification_node::children, image_classification_node::children_number, image_classifier::class_number, image_classification_node::depth, image_classification_node::end_recursion(), image_classification_node::expand(), image_classifier::image_height, image_classifier::image_width, image_classification_node::index, image_classifier::LearnProgression, max_depth, image_classification_tree::node_number(), image_classification_tree::root, image_classification_node::set_Dot(), tree_number, and trees.
Referenced by planar_object_recognizer::learn().
void image_classification_forest::refine (example_generator * vg, int call_number) [virtual]
Implements image_classifier.
Definition at line 211 of file image_classification_forest.cpp.
References image_classification_node::children, image_classifier::class_number, image_classification_node::d1, image_classification_node::d2, FOREST_REFINEMENT, example_generator::generate_random_examples(), image_classification_node::is_leaf(), image_classifier::LearnProgression, image_classification_node::P, example_generator::release_examples(), trees, and weights.
Referenced by planar_object_recognizer::learn().
void image_classification_forest::restore_occurances ()
Definition at line 262 of file image_classification_forest.cpp.
References image_classifier::class_number, trees, and weights.
void image_classification_forest::reset_class_occurances (int class_index)
Definition at line 273 of file image_classification_forest.cpp.
References trees, and weights.
void image_classification_forest::test (example_generator * vg, int call_number) [virtual]
Implements image_classifier.
Definition at line 281 of file image_classification_forest.cpp.
References image_classifier::class_number, example_generator::generate_random_examples(), GENERATING_TESTING_SET, image_classifier::LearnProgression, misclassification_rates, recognize(), example_generator::release_examples(), and thresholds.
Referenced by planar_object_recognizer::learn().
int image_classification_forest::recognize (image_class_example * pv, float * confidence = 0, int tree_number = -1) [virtual]
Implements image_classifier.
Definition at line 418 of file image_classification_forest.cpp.
References image_classifier::class_number, and posterior_probabilities().
Referenced by test().
float * image_classification_forest::posterior_probabilities (image_class_example * pv, int tree_number = -1) [virtual]
Implements image_classifier.
Definition at line 439 of file image_classification_forest.cpp.
References image_classifier::class_number.
Referenced by planar_object_recognizer::match_points(), and recognize().
void image_classification_forest::posterior_probabilities (image_class_example * pv, float * pp, int tree_number = -1) [virtual]
Definition at line 448 of file image_classification_forest.cpp.
References image_classifier::class_number, and trees.
void image_classification_forest::change_class_number_and_reset_probabilities (int new_class_number)
Definition at line 497 of file image_classification_forest.cpp.
References image_classifier::class_number, trees, and weights.
bool image_classification_forest::load (string directory_name) [virtual]
Reimplemented from image_classifier.
Definition at line 50 of file image_classification_forest.cpp.
References image_classifier::class_number, image_classifier::image_height, image_classifier::image_width, image_classification_tree::load(), max_depth, misclassification_rates, thresholds, trees, and weights.
Referenced by planar_object_recognizer::load().
bool image_classification_forest::save (string directory_name) [virtual]
Reimplemented from image_classifier.
Definition at line 517 of file image_classification_forest.cpp.
References image_classifier::class_number, misclassification_rates, thresholds, trees, and weights.
Referenced by planar_object_recognizer::save().
bool image_classification_forest::is_ok () [inline]
Definition at line 62 of file image_classification_forest.h.
References trees.
Member Data Documentation
float* image_classification_forest::thresholds
Definition at line 56 of file image_classification_forest.h.
Referenced by image_classification_forest(), load(), save(), test(), and ~image_classification_forest().
float* image_classification_forest::misclassification_rates
Definition at line 57 of file image_classification_forest.h.
Referenced by image_classification_forest(), load(), save(), test(), and ~image_classification_forest().
vector<image_classification_tree *> image_classification_forest::trees
Definition at line 65 of file image_classification_forest.h.
Referenced by change_class_number_and_reset_probabilities(), create_trees_at_random(), is_ok(), load(), posterior_probabilities(), refine(), reset_class_occurances(), restore_occurances(), save(), and ~image_classification_forest().
int image_classification_forest::tree_number
Definition at line 66 of file image_classification_forest.h.
Referenced by create_trees_at_random(), and image_classification_forest().
int image_classification_forest::max_depth
Definition at line 66 of file image_classification_forest.h.
Referenced by create_trees_at_random(), image_classification_forest(), and load().
float* image_classification_forest::weights
Definition at line 68 of file image_classification_forest.h.
Referenced by change_class_number_and_reset_probabilities(), image_classification_forest(), load(), refine(), reset_class_occurances(), restore_occurances(), save(), and ~image_classification_forest().
string image_classification_forest::directory_name
Definition at line 70 of file image_classification_forest.h.
Referenced by set_saving_directory_name().
The documentation for this class was generated from the following files:
/home/julian/devel/artvertiser/garfeild/viewsets/image_classification_forest.h
/home/julian/devel/artvertiser/garfeild/viewsets/image_classification_forest.cpp