bazar: /home/julian/devel/artvertiser/samples/artvertiser/draw.cpp File Reference
draw.cpp File Reference
#include <iostream>
#include <sstream>
#include <vector>
#include <cv.h>
#include <highgui.h>
#include <map>
#include <stdio.h>
#include <time.h>
#include <calib/camera.h>
#include "multigrab.h"
#include <GL/glut.h>
#include "/usr/include/freetype2/freetype/config/ftconfig.h"
#include <FTGL/ftgl.h>
Classes
struct artvert_struct
Defines
#define IsRGB(s) ((s[0] == 'R') && (s[1] == 'G') && (s[2] == 'B'))
#define IsBGR(s) ((s[0] == 'B') && (s[1] == 'G') && (s[2] == 'R'))
#define GL_CLAMP_TO_BORDER 0x812D
#define GL_MIRROR_CLAMP_EXT 0x8742
#define WIDTH 640
#define HEIGHT 480
Typedefs
typedef std::vector
< artvert_struct > artverts_list
typedef std::vector< IplImage > imgVec
Functions
static void photo_start ()
Starts photometric calibration.
static void geom_calib_start (bool cache)
Start geometric calibration. If the calibration can be loaded from disk, continue directly with photometric calibration.
artverts_list artverts (5)
static void drawText (IplImage *img, const char *text, CvPoint point, CvFont *font, CvScalar colour, double size)
static std::vector< int > readROI (const char *filename)
static void reshape (int width, int height)
GLUT callback on window size change.
static void usage (const char *s)
Print a command line help and exit.
static bool init (int argc, char **argv)
Initialize everything.
static void keyboard (unsigned char c, int x, int y)
static void emptyWindow ()
int main (int argc, char *argv[])
static bool drawBackground (IplTexture *tex)
Draw a frame contained in an IplTexture object on an OpenGL viewport.
static void geom_calib_draw (void)
A draw callback during camera calibration.
static void geom_calib_end ()
Called when geometric calibration ends. It makes sure that the CamAugmentation object is ready to work.
static void geom_calib_idle (void)
static void photo_draw (void)
static void photo_idle ()
Variables
MultiGrab * multi = 0
int geom_calib_nb_homography
CamCalibration * calib = 0
int current_cam = 0
IplTexture * frameTexture = 0
IplTexture * tex = 0
IplImage * image = 0
bool frameOK = false
int nbLightMeasures = 0
bool cacheLight = false
bool dynamicLight = false
bool sphereObject = false
bool avi_play = false
CvPoint projPts [4]
char * image_path
CvCapture * capture = 0
CvCapture * avi_capture = 0
IplImage * avi_image = 0
IplImage * avi_frame = 0
int avi_init = 0
int foundMatch = 0
int augment = 0
IplImage * image1 = cvLoadImage("artvert1.png")
IplImage * image2 = cvLoadImage("artvert2.png")
IplImage * image3 = cvLoadImage("artvert3.png")
IplImage * image4 = cvLoadImage("artvert4.png")
IplImage * image5 = cvLoadImage("artvert5.png")
int cnt = 0
std::vector< int > roiVec
CvFont font
CvFont fontbold
GLenum format
GLuint imageID
static FTFont * ftglFont
Define Documentation
#define GL_CLAMP_TO_BORDER 0x812D
Definition at line 139 of file draw.cpp.
#define GL_MIRROR_CLAMP_EXT 0x8742
Definition at line 141 of file draw.cpp.
#define HEIGHT 480
Definition at line 144 of file draw.cpp.
#define IsBGR (s) ((s[0] == 'B') && (s[1] == 'G') && (s[2] == 'R'))
Definition at line 136 of file draw.cpp.
#define IsRGB (s) ((s[0] == 'R') && (s[1] == 'G') && (s[2] == 'B'))
Definition at line 135 of file draw.cpp.
#define WIDTH 640
Definition at line 143 of file draw.cpp.
Typedef Documentation
typedef std::vector<artvert_struct> artverts_list
Definition at line 119 of file draw.cpp.
typedef std::vector<IplImage> imgVec
Definition at line 123 of file draw.cpp.
Function Documentation
artverts_list artverts (5)
static bool drawBackground (IplTexture * tex) [static]
Draw a frame contained in an IplTexture object on an OpenGL viewport.
Definition at line 375 of file draw.cpp.
References IplTexture::disableTexture(), IplTexture::getIm(), IplTexture::loadTexture(), IplTexture::u(), and IplTexture::v().
static void drawText (IplImage * img, const char * text, CvPoint point, CvFont * font, CvScalar colour, double size) [static]
Definition at line 168 of file draw.cpp.
static void emptyWindow () [static]
Definition at line 344 of file draw.cpp.
static void geom_calib_draw (void) [static]
A draw callback during camera calibration.
GLUT calls that function during camera calibration when repainting the window is required. During geometric calibration, no 3D is known: we just plot 2d points where some feature points have been recognized.
Definition at line 421 of file draw.cpp.
References MultiGrab::cams, PyrImage::convCoordf(), current_cam, drawBackground(), image_object_point_match::image_point, image_object_point_match::inlier, planar_object_recognizer::match_number, planar_object_recognizer::matches, planar_object_recognizer::object_is_detected, keypoint::scale, keypoint::u, and keypoint::v.
static void geom_calib_end () [static]
Called when geometric calibration ends. It makes sure that the CamAugmentation object is ready to work.
Definition at line 469 of file draw.cpp.
References CalibModel::augm, CamAugmentation::LoadOptimalStructureFromFile(), and MultiGrab::model.
static void geom_calib_idle (void) [static]
Called by GLUT during geometric calibration when there's nothing else to do. This function grab frames from camera(s), run the 2D detection on every image, and keep the result in memory for calibration. When enough homographies have been detected, it tries to actually calibrate the cameras.
Definition at line 488 of file draw.cpp.
References add_detected_homography(), CamCalibration::AddHomography(), CamCalibration::Calibrate(), MultiGrab::cams, current_cam, geom_calib_end(), geom_calib_nb_homography, MultiGrab::grabFrames(), photo_start(), CamCalibration::PrintOptimizedResultsToFile1(), and IplTexture::setImage().
static void geom_calib_start (bool cache) [static]
Start geometric calibration. If the calibration can be loaded from disk, continue directly with photometric calibration.
Definition at line 543 of file draw.cpp.
References CamCalibration::AddCamera(), CalibModel::augm, MultiGrab::cams, geom_calib_draw(), geom_calib_idle(), geom_calib_nb_homography, CamAugmentation::LoadOptimalStructureFromFile(), MultiGrab::model, and photo_start().
static bool init (int argc, char ** argv) [static]
Initialize everything.
Parse the command line
Initialize all the cameras
Load or interactively build a model, with its classifier.
Set the GLUT callbacks for geometric calibration or, if already done, for photometric calibration.
Definition at line 246 of file draw.cpp.
References artverts(), avi_capture, avi_play, cacheLight, geom_calib_start(), image1, image2, image3, image4, image5, image_path, MultiGrab::init(), modelFile, readROI(), roiVec, and usage().
static void keyboard (unsigned char c, int x, int y) [static]
The keyboard callback: reacts to '+' and '-' to change the viewed cam, 'q' exits. 'd' turns on/off the dynamic lightmap update. 'f' goes fullscreen.
Definition at line 314 of file draw.cpp.
References augment, avi_play, cnt, current_cam, and dynamicLight.
int main (int argc, char * argv[])
Definition at line 349 of file draw.cpp.
References emptyWindow(), ftglFont, HEIGHT, init(), keyboard(), reshape(), and WIDTH.
static void photo_draw (void) [static]
The paint callback during photometric calibration and augmentation. In this case, we have access to 3D data. Thus, we can augment the calibration target with cool stuff.
Definition at line 567 of file draw.cpp.
References artverts(), CalibModel::augm, augment, avi_capture, avi_frame, avi_image, avi_play, MultiGrab::cams, cnt, current_cam, cvmGet(), LightMap::disableShader(), drawBackground(), LightMap::enableShader(), PerspectiveProjection::flip(), format, foundMatch, frameOK, ftglFont, IplTexture::getIm(), CamAugmentation::GetObjectToWorld(), CamAugmentation::GetProjectionMatrix(), PerspectiveCamera::getWorldToEyeMat(), HEIGHT, image, CalibModel::image, imageID, IsBGR, LightMap::isReady(), PerspectiveCamera::loadTdir(), Mat3x4::m, M_PI, CalibModel::map, CamCalibration::Mat3x4Mul(), MultiGrab::model, Mat3x4::mul(), roiVec, PerspectiveCamera::setGlModelView(), PerspectiveProjection::setGlProjection(), IplTexture::setImage(), Mat3x4::setInverseByTranspose(), PerspectiveProjection::setPlanes(), Mat3x4::setRotate(), Mat3x4::setTranslate(), PerspectiveCamera::setWorldToEyeMat(), Mat3x4::transform(), and WIDTH.
static void photo_idle () [static]
GLUT calls this during photometric calibration or augmentation phase when there's nothing else to do. This function does the 2D detection and bundle adjusts the 3D pose of the calibration pattern. Then, it extracts the surface normal, and pass all the lighting measurements to the LightMap object. When enough is collected, the lightmap is computed.
Definition at line 869 of file draw.cpp.
References CamAugmentation::Accomodate(), add_detected_homography(), CamAugmentation::AddHomography(), LightMap::addNormal(), CalibModel::augm, MultiGrab::cams, CamAugmentation::Clear(), LightMap::computeLightParams(), current_cam, dynamicLight, frameOK, CamAugmentation::GetObjectToWorld(), MultiGrab::grabFrames(), LightMap::isReady(), CalibModel::map, MultiGrab::model, nbLightMeasures, LightMap::nbNormals(), LightMap::save(), and IplTexture::setImage().
static void photo_start () [static]
Starts photometric calibration.
Definition at line 928 of file draw.cpp.
References MultiGrab::allocLightCollector(), cacheLight, LightMap::load(), CalibModel::map, MultiGrab::model, nbLightMeasures, photo_draw(), and photo_idle().
static std::vector<int> readROI (const char * filename) [static]
Definition at line 176 of file draw.cpp.
static void reshape (int width, int height) [static]
GLUT callback on window size change.
Definition at line 212 of file draw.cpp.
References HEIGHT, and WIDTH.
static void usage (const char * s) [static]
Print a command line help and exit.
Definition at line 224 of file draw.cpp.
Variable Documentation
int augment = 0
Definition at line 99 of file draw.cpp.
CvCapture* avi_capture = 0
Definition at line 94 of file draw.cpp.
IplImage* avi_frame = 0
Definition at line 96 of file draw.cpp.
IplImage* avi_image = 0
Definition at line 95 of file draw.cpp.
int avi_init = 0
Definition at line 97 of file draw.cpp.
bool avi_play = false
Definition at line 85 of file draw.cpp.
bool cacheLight = false
Definition at line 82 of file draw.cpp.
CamCalibration* calib = 0
Definition at line 72 of file draw.cpp.
CvCapture* capture = 0
Definition at line 93 of file draw.cpp.
int cnt = 0
Definition at line 124 of file draw.cpp.
int current_cam = 0
Definition at line 73 of file draw.cpp.
bool dynamicLight = false
Definition at line 83 of file draw.cpp.
CvFont font
Definition at line 129 of file draw.cpp.
CvFont fontbold
Definition at line 129 of file draw.cpp.
GLenum format
Definition at line 132 of file draw.cpp.
int foundMatch = 0
Definition at line 98 of file draw.cpp.
bool frameOK = false
Definition at line 80 of file draw.cpp.
IplTexture* frameTexture = 0
Definition at line 75 of file draw.cpp.
FTFont* ftglFont [static]
Definition at line 148 of file draw.cpp.
int geom_calib_nb_homography
Definition at line 71 of file draw.cpp.
IplImage* image = 0
Definition at line 78 of file draw.cpp.
IplImage* image1 = cvLoadImage("artvert1.png")
Definition at line 102 of file draw.cpp.
IplImage* image2 = cvLoadImage("artvert2.png")
Definition at line 103 of file draw.cpp.
IplImage* image3 = cvLoadImage("artvert3.png")
Definition at line 104 of file draw.cpp.
IplImage* image4 = cvLoadImage("artvert4.png")
Definition at line 105 of file draw.cpp.
IplImage* image5 = cvLoadImage("artvert5.png")
Definition at line 106 of file draw.cpp.
char* image_path
Definition at line 92 of file draw.cpp.
GLuint imageID
Definition at line 133 of file draw.cpp.
MultiGrab* multi = 0
Definition at line 69 of file draw.cpp.
int nbLightMeasures = 0
Definition at line 81 of file draw.cpp.
CvPoint projPts[4]
Definition at line 87 of file draw.cpp.
std::vector<int> roiVec
Definition at line 126 of file draw.cpp.
bool sphereObject = false
Definition at line 84 of file draw.cpp.
IplTexture* tex = 0
Definition at line 76 of file draw.cpp.