bazar: /home/julian/devel/artvertiser/samples/filedetect/filedetect.cpp File Reference
filedetect.cpp File Reference
A planar_object_recognizer example.
#include <iostream>
#include <garfeild.h>
#include <highgui.h>
Functions
int main (int argc, char *argv[])
Detailed Description
A planar_object_recognizer example.
This very simple example loads a planar_object_recognizer object and detects a pattern in the images passed on the command line.
Definition in file filedetect.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 37 of file filedetect.cpp.
References planar_object_recognizer::build_with_cache(), planar_object_recognizer::create_result_image(), planar_object_recognizer::detect(), planar_object_recognizer::match_score_threshold, planar_object_recognizer::max_ransac_iterations, planar_object_recognizer::min_view_rate, modelFile, planar_object_recognizer::non_linear_refine_threshold, planar_object_recognizer::ransac_dist_threshold, and planar_object_recognizer::views_number.