bazar: /home/julian/devel/artvertiser/samples/fullcalib/fullcalib-gl.cpp File Reference
fullcalib-gl.cpp File Reference
#include <iostream>
#include "cv.h"
#include "highgui.h"
#include "calibmodel.h"
Functions
void show_result (planar_object_recognizer &recognizer, IplImage *video, IplImage *dst)
static void augment_scene (CalibModel &model, IplImage *frame, IplImage *display)
bool add_detected_homography (planar_object_recognizer &detector, CamCalibration &calib)
bool add_detected_homography (planar_object_recognizer &detector, CamAugmentation &a)
bool geometric_calibration (CalibModel &model, CvCapture *capture, bool cache)
bool photometric_calibration (CalibModel &model, CvCapture *capture, int nbImages, bool cache)
void usage (const char *s)
int main (int argc, char **argv)
Function Documentation
bool add_detected_homography (planar_object_recognizer & detector, CamAugmentation & a)
bool add_detected_homography (planar_object_recognizer & detector, CamCalibration & calib)
Definition at line 367 of file fullcalib-gl.cpp.
References CamCalibration::AddHomography(), PyrImage::convCoordf(), planar_object_recognizer::H, image_object_point_match::image_point, image_object_point_match::inlier, object_keypoint::M, planar_object_recognizer::match_number, planar_object_recognizer::matches, image_object_point_match::object_point, object_keypoint::scale, keypoint::scale, keypoint::u, and keypoint::v.
static void augment_scene (CalibModel & model, IplImage * frame, IplImage * display) [static]
Definition at line 307 of file fullcalib-gl.cpp.
References CalibModel::augm, CalibModel::corners, cvPoint(), CalibModel::detector, LightMap::getBias(), LightMap::getGain(), CamAugmentation::GetObjectToWorld(), CamAugmentation::GetProjectionMatrix(), CalibModel::image, CalibModel::map, planar_object_recognizer::object_is_detected, projPts, and LightMap::readMap().
bool geometric_calibration (CalibModel & model, CvCapture * capture, bool cache)
Definition at line 102 of file fullcalib-gl.cpp.
References add_detected_homography(), CamCalibration::AddCamera(), CalibModel::augm, calib, CamCalibration::Calibrate(), planar_object_recognizer::detect(), CalibModel::detector, CamAugmentation::LoadOptimalStructureFromFile(), CamCalibration::PrintOptimizedResultsToFile1(), and show_result().
int main (int argc, char ** argv)
Definition at line 40 of file fullcalib-gl.cpp.
References CalibModel::buildCached(), capture, geometric_calibration(), modelFile, photometric_calibration(), and usage().
bool photometric_calibration (CalibModel & model, CvCapture * capture, int nbImages, bool cache)
Definition at line 184 of file fullcalib-gl.cpp.
References CamAugmentation::Accomodate(), add_detected_homography(), LightMap::addNormal(), CalibModel::augm, augment_scene(), LightCollector::averageImage(), LightCollector::avgChannels, CamAugmentation::Clear(), LightMap::computeLightParams(), planar_object_recognizer::detect(), CalibModel::detector, LightCollector::drawGrid(), LightMap::getBias(), LightMap::getGain(), IplTexture::getIm(), CamAugmentation::GetObjectToWorld(), planar_object_recognizer::H, LightMap::isReady(), LightMap::load(), LightMap::map, CalibModel::map, planar_object_recognizer::object_is_detected, LightMap::reflc, and LightMap::save().
void show_result (planar_object_recognizer & recognizer, IplImage * video, IplImage * dst)
void usage (const char * s)
Definition at line 29 of file fullcalib-gl.cpp.