bazar: /home/julian/devel/artvertiser/starter/general/general.h File Reference
general.h File Reference
#include <stdlib.h>
Defines
#define M_PI 3.141592653589793238462643383279
Functions
float rand_01 (void)
float rand_m1p1 (void)
float rand (float min, float max)
int gf_sqr (const int x)
float gf_sqr (const float x)
Define Documentation
#define M_PI 3.141592653589793238462643383279
Definition at line 31 of file general.h.
Function Documentation
float gf_sqr (const float x) [inline]
Definition at line 61 of file general.h.
int gf_sqr (const int x) [inline]
Definition at line 56 of file general.h.
float rand (float min, float max) [inline]
Definition at line 51 of file general.h.
References rand_01().
Referenced by affine_image_generator::add_white_noise(), fill_random(), affine_image_generator::generate_affine_image(), affine_image_generator::generate_random_affine_transformation(), mcvAddWhiteNoise(), mcvCreateRandomImage(), mcvRainbowColor(), mcvReplaceByNoise(), rand_01(), affine_image_generator::replace_by_noise(), affine_image_generator::set_noise_level(), and planar_object_recognizer::three_random_correspondences().
float rand_01 (void) [inline]
Definition at line 41 of file general.h.
References rand().
Referenced by affine_image_generator::generate_random_affine_transformation(), rand(), and rand_m1p1().
float rand_m1p1 (void) [inline]
Definition at line 46 of file general.h.
References rand_01().
Referenced by affine_image_generator::generate_random_examples(), and image_classification_node::set_Dot().