bazar: /home/julian/devel/artvertiser/samples/interactive/interactive.cpp File Reference
interactive.cpp File Reference
An interactive example of 2D planar object training and detection. This example uses HighGUI to interactively propose to the user to create a planar model. It then shows live 2D detection of this object.
#include <iostream>
#include "cv.h"
#include "highgui.h"
#include <garfeild.h>
#include <config.h>
#include <sys/time.h>
Functions
void acquire_model (CvCapture *capture, planar_object_recognizer &detector)
void show_result (planar_object_recognizer &recognizer, IplImage *video, IplImage **dst)
void usage (const char *s)
int main (int argc, char **argv)
Variables
char * modelFile = "model.jpg"
Detailed Description
An interactive example of 2D planar object training and detection. This example uses HighGUI to interactively propose to the user to create a planar model. It then shows live 2D detection of this object.
Definition in file interactive.cpp.
Function Documentation
void acquire_model (CvCapture * capture, planar_object_recognizer & detector)
Examples:
singlecalib.cpp.
Definition at line 186 of file interactive.cpp.
References planar_object_recognizer::build(), modelFile, and planar_object_recognizer::save().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 31 of file interactive.cpp.
References acquire_model(), planar_object_recognizer::build_with_cache(), capture, planar_object_recognizer::detect(), planar_object_recognizer::match_score_threshold, modelFile, show_result(), and usage().
void show_result (planar_object_recognizer & recognizer, IplImage * video, IplImage ** dst)
Definition at line 165 of file interactive.cpp.
References PyrImage::convCoordf(), cvPoint(), image_object_point_match::image_point, image_object_point_match::inlier, planar_object_recognizer::match_number, planar_object_recognizer::matches, planar_object_recognizer::object_is_detected, keypoint::scale, keypoint::u, and keypoint::v.
void usage (const char * s)
Definition at line 25 of file interactive.cpp.
Variable Documentation
char* modelFile = "model.jpg"
Definition at line 18 of file interactive.cpp.