bazar: /home/julian/devel/artvertiser/garfeild/lightcalib/lightmap.cpp File Reference
lightmap.cpp File Reference
#include <stdio.h>
#include <iostream>
#include <fstream>
#include "lightmap.h"
#include <highgui.h>
Defines
#define M_PI 3.1415926535897932384626433832795
Functions
static void normalize (float normal[3])
static bool saveMat (const CvMat *m, const char *fn)
static CvGrowMat * loadMat (const char *fn)
Define Documentation
#define M_PI 3.1415926535897932384626433832795
Definition at line 11 of file lightmap.cpp.
Function Documentation
static CvGrowMat* loadMat (const char * fn) [static]
Definition at line 522 of file lightmap.cpp.
References CvGrowMat::resize().
Referenced by LightMap::load().
static void normalize (float normal[3]) [static]
Definition at line 431 of file lightmap.cpp.
Referenced by LightMap::addNormalCalib().
static bool saveMat (const CvMat * m, const char * fn) [static]
Definition at line 504 of file lightmap.cpp.
Referenced by LightMap::save().