bazar: /home/julian/devel/artvertiser/starter/math/linear_algebra.cpp File Reference
linear_algebra.cpp File Reference
#include <iostream>
#include <math.h>
#include "linear_algebra.h"
#include <general/general.h>
Functions
double gfla_norme (double v1, double v2, double v3)
double gfla_normalize_3 (double v[3])
void gfla_scale_3 (const double s, double v[3])
void gfla_scale_3 (const double s, const double v[3], double sv[3])
void gfla_opp_3 (double v[3])
void gfla_add_3 (const double u[3], const double v[3], double w[3])
void gfla_sub_3 (const double u[3], const double v[3], double w[3])
void gfla_cross_product (const double v1[3], const double v2[3], double v1v2[3])
double gfla_dot_product (const double v1[3], const double v2[3])
void gfla_copy_3 (const double v[3], double copy[3])
void gfla_copy_3x3 (const double M[3][3], double copy[3][3])
void gfla_copy_3x4 (const double M[3][4], double copy[3][4])
double gfla_det (const double M[3][3])
double gfla_det (const double M11, const double M12, const double M21, const double M22)
double gfla_det (const double M11, const double M12, const double M13, const double M21, const double M22, const double M23, const double M31, const double M32, const double M33)
void gfla_get_rotation_from_kappa (double R[3][3], const double kappa)
void gfla_get_rotation_from_phi (double R[3][3], const double phi)
void gfla_get_rotation_from_omega (double R[3][3], const double omega)
void gfla_get_rotation_from_euler_angles (double R[3][3], const double omega, const double phi, const double kappa)
int gfla_get_euler_angles_from_rotation (const double R[3][3], double *omega, double *phi, double *kappa)
void gfla_mul_scale_mat_3x3 (double s, double M[3][3], double sM[3][3])
void gfla_mul_mat_vect_3x3 (const double M[3][3], const double v[3], double Mv[3])
void gfla_mul_T_mat_vect_3x3 (const double M[3][3], const double v[3], double tMv[3])
void gfla_mul_mat_vect_3x4 (const double M[3][4], const double v[3], double Mv[3])
void gfla_mul_mat_3x3x4 (const double M[3][3], const double N[3][4], double MN[3][4])
void gfla_inverse_3 (double A[3][3], double invA[3][3])
void gfla_print_mat_3x3 (ostream &o, double M[3][3])
void gfla_print_mat_3x4 (ostream &o, double M[3][4])
void gfla_print_mat_4x4 (ostream &o, double *M)
Function Documentation
void gfla_add_3 (const double u[3], const double v[3], double w[3])
Definition at line 74 of file linear_algebra.cpp.
Referenced by projection_matrix::set_external_parameters().
void gfla_copy_3 (const double v[3], double copy[3])
Definition at line 101 of file linear_algebra.cpp.
Referenced by projection_matrix::operator=(), and projection_matrix::set_external_parameters().
void gfla_copy_3x3 (const double M[3][3], double copy[3][3])
Definition at line 108 of file linear_algebra.cpp.
Referenced by projection_matrix::operator=(), and projection_matrix::set_external_parameters().
void gfla_copy_3x4 (const double M[3][4], double copy[3][4])
Definition at line 115 of file linear_algebra.cpp.
Referenced by projection_matrix::get_3x4_matrix().
void gfla_cross_product (const double v1[3], const double v2[3], double v1v2[3])
Definition at line 88 of file linear_algebra.cpp.
Referenced by projection_matrix::set_camera_centre_and_lookat_point(), projection_matrix::set_external_parameters(), and projection_matrix::visible_triangle().
double gfla_det (const double M11, const double M12, const double M13, const double M21, const double M22, const double M23, const double M31, const double M32, const double M33)
Definition at line 140 of file linear_algebra.cpp.
double gfla_det (const double M11, const double M12, const double M21, const double M22)
Definition at line 134 of file linear_algebra.cpp.
double gfla_det (const double M[3][3])
Definition at line 124 of file linear_algebra.cpp.
Referenced by projection_matrix::set_3x4_matrix(), and solve_ls().
double gfla_dot_product (const double v1[3], const double v2[3])
Definition at line 95 of file linear_algebra.cpp.
Referenced by projection_matrix::visible_triangle().
int gfla_get_euler_angles_from_rotation (const double R[3][3], double * omega, double * phi, double * kappa)
Definition at line 196 of file linear_algebra.cpp.
References M_PI.
Referenced by projection_matrix::get_external_parameters().
void gfla_get_rotation_from_euler_angles (double R[3][3], const double omega, const double phi, const double kappa)
R = R(kappa) * R(phi) * R(omega)
Definition at line 173 of file linear_algebra.cpp.
Referenced by projection_matrix::set_external_parameters().
void gfla_get_rotation_from_kappa (double R[3][3], const double kappa)
Definition at line 149 of file linear_algebra.cpp.
void gfla_get_rotation_from_omega (double R[3][3], const double omega)
Definition at line 163 of file linear_algebra.cpp.
void gfla_get_rotation_from_phi (double R[3][3], const double phi)
Definition at line 156 of file linear_algebra.cpp.
void gfla_inverse_3 (double A[3][3], double invA[3][3])
Definition at line 286 of file linear_algebra.cpp.
void gfla_mul_mat_3x3x4 (const double M[3][3], const double N[3][4], double MN[3][4])
Definition at line 272 of file linear_algebra.cpp.
Referenced by projection_matrix::set_GL_PROJECTION().
void gfla_mul_mat_vect_3x3 (const double M[3][3], const double v[3], double Mv[3])
Definition at line 230 of file linear_algebra.cpp.
Referenced by projection_matrix::read_from_matchmover_output().
void gfla_mul_mat_vect_3x4 (const double M[3][4], const double v[3], double Mv[3])
Definition at line 262 of file linear_algebra.cpp.
Referenced by projection_matrix::project().
void gfla_mul_scale_mat_3x3 (double s, double M[3][3], double sM[3][3])
Definition at line 223 of file linear_algebra.cpp.
void gfla_mul_T_mat_vect_3x3 (const double M[3][3], const double v[3], double tMv[3])
Definition at line 252 of file linear_algebra.cpp.
double gfla_normalize_3 (double v[3])
Definition at line 37 of file linear_algebra.cpp.
Referenced by projection_matrix::get_V(), projection_matrix::set_camera_centre_and_lookat_point(), and projection_matrix::set_external_parameters().
double gfla_norme (double v1, double v2, double v3)
Definition at line 32 of file linear_algebra.cpp.
Referenced by projection_matrix::get_V().
void gfla_opp_3 (double v[3])
Definition at line 67 of file linear_algebra.cpp.
Referenced by projection_matrix::read_from_matchmover_output().
void gfla_print_mat_3x3 (ostream & o, double M[3][3])
Definition at line 338 of file linear_algebra.cpp.
void gfla_print_mat_3x4 (ostream & o, double M[3][4])
Definition at line 348 of file linear_algebra.cpp.
void gfla_print_mat_4x4 (ostream & o, double * M)
Definition at line 358 of file linear_algebra.cpp.
void gfla_scale_3 (const double s, const double v[3], double sv[3])
Definition at line 60 of file linear_algebra.cpp.
void gfla_scale_3 (const double s, double v[3])
Definition at line 53 of file linear_algebra.cpp.
Referenced by projection_matrix::set_external_parameters().
void gfla_sub_3 (const double u[3], const double v[3], double w[3])
Definition at line 81 of file linear_algebra.cpp.
Referenced by projection_matrix::set_external_parameters().