bazar: /home/julian/devel/artvertiser/starter/image/mcv.cpp File Reference
mcv.cpp File Reference
#include <iostream>
#include <math.h>
#include <cv.h>
#include <highgui.h>
#include "mcv.h"
Functions
CvSize mcvSize (IplImage *image)
void mcvSmooth (IplImage *image, IplImage *smoothed_image, int smooth_type, int aperture)
float mcvGaussianDerivative (IplImage *image, int x, int y, int order_x, int order_y, float sigma)
IplImage * mcvGradientNorm2 (IplImage *image, int aperture)
void mcvSetBorder (IplImage *image, int border, int value)
void mcvSetBorder (IplImage *image, int border_size)
IplImage * mcvColorToGray (IplImage *colorImage)
IplImage * mcvGrayToColor (IplImage *grayImage)
void mcvHSV2RGB (float H, float S, float V, int &R, int &G, int &B)
IplImage * mcvFloatToHue (IplImage *floatImage, int curve_number)
IplImage * mcvFloatToGray (IplImage *floatImage, int curve_number)
IplImage * showLocalMinima (IplImage *image)
IplImage * showLocalMaxima (IplImage *image)
void mcvSwapRandB (IplImage *image)
void mcvScaleTo0_255 (IplImage *original, IplImage *scaled)
int mcvSaveImage (const char *filename, IplImage *image, bool verbose)
int mcvSaveImage (const char *generic_filename, int index, IplImage *image, bool verbose)
IplImage * mcvCreateSimilarImage (IplImage *image)
IplImage * mcvLoadImage (const char *filename, int code, bool verbose)
IplImage * mcvLoadImage (const char *generic_filename, int index, int code, bool verbose)
void mcvSquare (IplImage *image, int x, int y, int size, CvScalar color, int width)
void mcvX (IplImage *image, int x, int y, int size, CvScalar color, int width)
void mcvCross (IplImage *image, int x, int y, int size, CvScalar color, int width)
void mcvCircle (IplImage *image, int x, int y, int size, CvScalar color, int thickness)
void mcvVisibleLine (IplImage *image, int x1, int y1, int x2, int y2, int thickness)
IplImage * mcvCreateRandomImage (CvSize size, int depth, int nChannels)
void mcvReplace (IplImage *image, int old_value, int new_value)
void mcvReplaceByNoise (IplImage *image, int value)
void mcvAddWhiteNoise (const IplImage *image, const int minNoise, const int maxNoise)
void mcvAddWhiteNoise (const IplImage *image, const int maxNoise)
void mcvChangeGamma (IplImage *image, float gamma)
void mcvCrop (IplImage *image, int x, int y, IplImage *croppedImage)
IplImage * mcvCrop (IplImage *image, int x, int y, int width, int height)
IplImage * mcvResize (IplImage *original_image, int new_width, int new_height)
IplImage * mcvZoom (IplImage *source, int xc, int yc, float zoom)
void mcvPut (IplImage *destImage, IplImage *imageToCopy, int x, int y)
void mcvDeinterlace (IplImage *image)
IplImage * mcvGetPatch (IplImage *image, int u, int v, int width, int height)
void mcvGetPatch (IplImage *image, IplImage *patch, int u, int v)
void imcvR3z (double Rz[3][3], double angle)
void imcvDiag3 (double D[3][3], double d1, double d2, double d3)
void imcvTransl3 (double T[3][3], double tx, double ty)
void imcvMul_MN3 (double A[3][3], double B[3][3], double AB[3][3])
void imcvMul_MNt3 (double A[3][3], double B[3][3], double ABt[3][3])
void imcvMul_MNMt3 (double M[3][3], double N[3][3], double MNMt[3][3])
void mcvComputeAffineTransfo (float *a, int u, int v, float theta, float phi, float lambda1, float lambda2, float tx, float ty)
CvScalar mcvRainbowColor (int index, float coeff)
Function Documentation
void imcvDiag3 (double D[3][3], double d1, double d2, double d3)
Definition at line 778 of file mcv.cpp.
Referenced by mcvComputeAffineTransfo().
void imcvMul_MN3 (double A[3][3], double B[3][3], double AB[3][3])
Definition at line 792 of file mcv.cpp.
Referenced by imcvMul_MNMt3(), and mcvComputeAffineTransfo().
void imcvMul_MNMt3 (double M[3][3], double N[3][3], double MNMt[3][3])
Definition at line 824 of file mcv.cpp.
References imcvMul_MN3(), and imcvMul_MNt3().
void imcvMul_MNt3 (double A[3][3], double B[3][3], double ABt[3][3])
Definition at line 808 of file mcv.cpp.
Referenced by imcvMul_MNMt3().
void imcvR3z (double Rz[3][3], double angle)
Definition at line 771 of file mcv.cpp.
Referenced by mcvComputeAffineTransfo().
void imcvTransl3 (double T[3][3], double tx, double ty)
Definition at line 785 of file mcv.cpp.
Referenced by mcvComputeAffineTransfo().
void mcvAddWhiteNoise (const IplImage * image, const int maxNoise)
Definition at line 617 of file mcv.cpp.
References rand().
void mcvAddWhiteNoise (const IplImage * image, const int minNoise, const int maxNoise)
Definition at line 590 of file mcv.cpp.
References mcvRow, and rand().
void mcvChangeGamma (IplImage * image, float gamma)
Definition at line 640 of file mcv.cpp.
void mcvCircle (IplImage * image, int x, int y, int size, CvScalar color, int thickness)
Definition at line 531 of file mcv.cpp.
References cvPoint().
Referenced by pyr_yape::save_image_of_detected_points(), and yape::save_image_of_detected_points().
IplImage* mcvColorToGray (IplImage * colorImage)
Definition at line 197 of file mcv.cpp.
void mcvComputeAffineTransfo (float * a, int u, int v, float theta, float phi, float lambda1, float lambda2, float tx, float ty)
Definition at line 841 of file mcv.cpp.
References imcvDiag3(), imcvMul_MN3(), imcvR3z(), and imcvTransl3().
Referenced by affine_image_generator::generate_Id_affine_transformation(), and affine_image_generator::generate_random_affine_transformation().
IplImage* mcvCreateRandomImage (CvSize size, int depth, int nChannels)
Definition at line 544 of file mcv.cpp.
References rand().
IplImage* mcvCreateSimilarImage (IplImage * image)
Definition at line 479 of file mcv.cpp.
IplImage* mcvCrop (IplImage * image, int x, int y, int width, int height)
Definition at line 680 of file mcv.cpp.
References mcvCrop().
void mcvCrop (IplImage * image, int x, int y, IplImage * croppedImage)
Definition at line 658 of file mcv.cpp.
Referenced by mcvCrop(), and mcvGetPatch().
void mcvCross (IplImage * image, int x, int y, int size, CvScalar color, int width)
Definition at line 525 of file mcv.cpp.
References cvPoint().
void mcvDeinterlace (IplImage * image)
Definition at line 742 of file mcv.cpp.
IplImage* mcvFloatToGray (IplImage * floatImage, int curve_number)
Definition at line 306 of file mcv.cpp.
References mcvRow.
IplImage* mcvFloatToHue (IplImage * floatImage, int curve_number)
Definition at line 259 of file mcv.cpp.
References mcvHSV2RGB(), and mcvRow.
float mcvGaussianDerivative (IplImage * image, int x, int y, int order_x, int order_y, float sigma)
Definition at line 72 of file mcv.cpp.
References mcvGet2D.
void mcvGetPatch (IplImage * image, IplImage * patch, int u, int v)
Definition at line 766 of file mcv.cpp.
References mcvCrop().
IplImage* mcvGetPatch (IplImage * image, int u, int v, int width, int height)
Definition at line 761 of file mcv.cpp.
References mcvCrop().
Referenced by affine_image_generator::preprocess_point_view(), and planar_object_recognizer::save_patch_before_and_after_correction().
IplImage* mcvGradientNorm2 (IplImage * image, int aperture)
Definition at line 115 of file mcv.cpp.
References mcvScaleTo0_255().
IplImage* mcvGrayToColor (IplImage * grayImage)
Definition at line 206 of file mcv.cpp.
Referenced by mcvPut(), pyr_yape::save_image_of_detected_points(), yape::save_image_of_detected_points(), planar_object_recognizer::save_image_of_model_points(), showLocalMaxima(), and showLocalMinima().
void mcvHSV2RGB (float H, float S, float V, int & R, int & G, int & B)
Definition at line 228 of file mcv.cpp.
Referenced by mcvFloatToHue().
IplImage* mcvLoadImage (const char * generic_filename, int index, int code, bool verbose)
Definition at line 500 of file mcv.cpp.
References mcvLoadImage().
IplImage* mcvLoadImage (const char * filename, int code, bool verbose)
Definition at line 484 of file mcv.cpp.
Referenced by planar_object_recognizer::build_with_cache(), planar_object_recognizer::load(), and mcvLoadImage().
void mcvPut (IplImage * destImage, IplImage * imageToCopy, int x, int y)
Definition at line 717 of file mcv.cpp.
References mcvGrayToColor().
Referenced by planar_object_recognizer::concat_model_and_input_images().
CvScalar mcvRainbowColor (int index, float coeff)
Definition at line 871 of file mcv.cpp.
References rand().
Referenced by planar_object_recognizer::draw_input_image_points(), pyr_yape::save_image_of_detected_points(), yape::save_image_of_detected_points(), and planar_object_recognizer::save_image_of_model_points().
void mcvReplace (IplImage * image, int old_value, int new_value)
Definition at line 566 of file mcv.cpp.
References mcvRow.
Referenced by affine_image_generator::generate_affine_image().
void mcvReplaceByNoise (IplImage * image, int value)
Definition at line 578 of file mcv.cpp.
References mcvRow, and rand().
IplImage* mcvResize (IplImage * original_image, int new_width, int new_height)
Definition at line 691 of file mcv.cpp.
int mcvSaveImage (const char * generic_filename, int index, IplImage * image, bool verbose)
Definition at line 468 of file mcv.cpp.
References mcvSaveImage().
int mcvSaveImage (const char * filename, IplImage * image, bool verbose)
Definition at line 431 of file mcv.cpp.
Referenced by affine_image_generator::generate_affine_image(), mcvSaveImage(), planar_object_recognizer::preprocess_points(), planar_object_recognizer::save(), pyr_yape::save_image_of_detected_points(), yape::save_image_of_detected_points(), planar_object_recognizer::save_image_of_model_points(), planar_object_recognizer::save_one_image_per_match(), planar_object_recognizer::save_one_image_per_match_input_to_model(), planar_object_recognizer::save_one_image_per_match_model_to_input(), and planar_object_recognizer::save_patch_before_and_after_correction().
void mcvScaleTo0_255 (IplImage * original, IplImage * scaled)
Definition at line 420 of file mcv.cpp.
Referenced by mcvGradientNorm2().
void mcvSetBorder (IplImage * image, int border_size)
Definition at line 163 of file mcv.cpp.
References mcvRow, and N.
void mcvSetBorder (IplImage * image, int border, int value)
Definition at line 143 of file mcv.cpp.
References mcvGet2D.
CvSize mcvSize (IplImage * image)
Definition at line 33 of file mcv.cpp.
void mcvSmooth (IplImage * image, IplImage * smoothed_image, int smooth_type, int aperture)
Definition at line 40 of file mcv.cpp.
void mcvSquare (IplImage * image, int x, int y, int size, CvScalar color, int width)
Definition at line 511 of file mcv.cpp.
References cvPoint().
void mcvSwapRandB (IplImage * image)
Definition at line 405 of file mcv.cpp.
void mcvVisibleLine (IplImage * image, int x1, int y1, int x2, int y2, int thickness)
Definition at line 536 of file mcv.cpp.
References cvPoint().
void mcvX (IplImage * image, int x, int y, int size, CvScalar color, int width)
Definition at line 519 of file mcv.cpp.
References cvPoint().
IplImage* mcvZoom (IplImage * source, int xc, int yc, float zoom)
Definition at line 700 of file mcv.cpp.
IplImage* showLocalMaxima (IplImage * image)
Definition at line 378 of file mcv.cpp.
References mcvGrayToColor(), and mcvRow.
IplImage* showLocalMinima (IplImage * image)
Definition at line 351 of file mcv.cpp.
References mcvGrayToColor(), and mcvRow.