bazar: /home/julian/devel/artvertiser/samples/multicam/multigrab.cpp File Reference
multigrab.cpp File Reference
#include "multigrab.h"
Functions
bool add_detected_homography (int n, planar_object_recognizer &detector, CamCalibration &calib)
bool add_detected_homography (int n, planar_object_recognizer &detector, CamAugmentation &a)
Function Documentation
bool add_detected_homography (int n, planar_object_recognizer & detector, CamAugmentation & a)
Definition at line 108 of file multigrab.cpp.
References CamAugmentation::AddHomography(), PyrImage::convCoordf(), planar_object_recognizer::H, image_object_point_match::image_point, image_object_point_match::inlier, object_keypoint::M, planar_object_recognizer::match_number, planar_object_recognizer::matches, image_object_point_match::object_point, object_keypoint::scale, keypoint::scale, keypoint::u, and keypoint::v.
bool add_detected_homography (int n, planar_object_recognizer & detector, CamCalibration & calib)
Definition at line 89 of file multigrab.cpp.
References CamCalibration::AddHomography(), PyrImage::convCoordf(), planar_object_recognizer::H, image_object_point_match::image_point, image_object_point_match::inlier, object_keypoint::M, planar_object_recognizer::match_number, planar_object_recognizer::matches, image_object_point_match::object_point, object_keypoint::scale, keypoint::scale, keypoint::u, and keypoint::v.