bazar: /home/julian/devel/artvertiser/starter/math/polynom_solver.cpp File Reference
polynom_solver.cpp File Reference
Functions to calculate roots of polynomials (Author: Mustafa Ozuysal, modified by Vincent Lepetit).
#include <math.h>
#include <iostream>
#include "polynom_solver.h"
#include <general/general.h>
Functions
int solve_deg2 (double a, double b, double c, double &x1, double &x2)
int solve_deg3 (double a, double b, double c, double d, double &x0, double &x1, double &x2)
Reference : Eric W.
int solve_deg4 (double a, double b, double c, double d, double e, double &x0, double &x1, double &x2, double &x3)
Reference : Eric W.
Detailed Description
Functions to calculate roots of polynomials (Author: Mustafa Ozuysal, modified by Vincent Lepetit).
Definition in file polynom_solver.cpp.
Function Documentation
int solve_deg2 (double a, double b, double c, double & x1, double & x2)
Definition at line 32 of file polynom_solver.cpp.
Referenced by ls_minimizer2::minimize_using_dogleg_from(), and solve_deg3().
int solve_deg3 (double a, double b, double c, double d, double & x0, double & x1, double & x2)
Reference : Eric W.
Weisstein. "Cubic Equation." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/CubicEquation.html
Returns:
Number of real roots found.
Definition at line 57 of file polynom_solver.cpp.
References M_PI, and solve_deg2().
Referenced by solve_deg4().
int solve_deg4 (double a, double b, double c, double d, double e, double & x0, double & x1, double & x2, double & x3)
Reference : Eric W.
Weisstein. "Quartic Equation." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/QuarticEquation.html
Returns:
Number of real roots found.
Definition at line 127 of file polynom_solver.cpp.
References E, and solve_deg3().