bazar: /home/julian/devel/artvertiser/samples/singlecalib/singlecalib.cpp File Reference
singlecalib.cpp File Reference
A single camera geometric calibration interactive example.
#include <iostream>
#include "cv.h"
#include "highgui.h"
#include <garfeild.h>
Functions
IplImage * acquire_model (CvCapture *capture)
void show_result (planar_object_recognizer &recognizer, IplImage *video, IplImage **dst)
bool add_detected_homography (planar_object_recognizer &detector, CamCalibration &calib)
void usage (const char *s)
int main (int argc, char **argv)
static void putText (IplImage *im, const char *text, CvPoint p, CvFont *f1, CvFont *f2)
Variables
char * modelFile = "model.jpg"
Detailed Description
A single camera geometric calibration interactive example.
Author:
Julien Pilet In this example, the user is asked to prepare a calibration pattern. After moving it around, geometric calibration of the camera is computed and saved on disk. The file augment3d.cpp shows how to use the resulting calibration to put a virtual 3D object on the target.
Definition in file singlecalib.cpp.
Function Documentation
IplImage * acquire_model (CvCapture * capture)
Definition at line 190 of file singlecalib.cpp.
References cvPoint(), font, fontbold, and putText().
bool add_detected_homography (planar_object_recognizer & detector, CamCalibration & calib)
int main (int argc, char ** argv)
Definition at line 33 of file singlecalib.cpp.
References acquire_model(), add_detected_homography(), CamCalibration::AddCamera(), planar_object_recognizer::build(), planar_object_recognizer::build_with_cache(), calib, CamCalibration::Calibrate(), capture, planar_object_recognizer::detect(), planar_object_recognizer::match_score_threshold, planar_object_recognizer::max_ransac_iterations, modelFile, planar_object_recognizer::non_linear_refine_threshold, CamCalibration::PrintOptimizedResultsToFile1(), planar_object_recognizer::ransac_dist_threshold, planar_object_recognizer::save(), show_result(), and usage().
static void putText (IplImage * im, const char * text, CvPoint p, CvFont * f1, CvFont * f2) [static]
Definition at line 184 of file singlecalib.cpp.
void show_result (planar_object_recognizer & recognizer, IplImage * video, IplImage ** dst)
void usage (const char * s)
Definition at line 25 of file singlecalib.cpp.
Variable Documentation
char* modelFile = "model.jpg"
Definition at line 19 of file singlecalib.cpp.