bazar: ProjObs Struct Reference
ProjObs Struct Reference
Public Member Functions
ProjObs ()
virtual int get_nb_measures () const
virtual void eval_func (const double *params, double *f, double *J, void **user_data) const
Public Attributes
double target [2]
int cam
int hom
int point
Static Public Attributes
static int parameterNumber = 0
Detailed Description
Definition at line 1579 of file CamCalibration.cpp.
Constructor & Destructor Documentation
ProjObs::ProjObs () [inline]
Definition at line 1586 of file CamCalibration.cpp.
Member Function Documentation
virtual int ProjObs::get_nb_measures () const [inline, virtual]
Implements ls_minimizer2::observation.
Definition at line 1589 of file CamCalibration.cpp.
void ProjObs::eval_func (const double * params, double * f, double * J, void ** user_data) const [virtual]
Implements ls_minimizer2::observation.
Definition at line 1609 of file CamCalibration.cpp.
References cvmGet(), CamCalibration::ExtractRotationTranslationFrom3x4Matrix(), hom, CamCalibration::HomogenousNormalizeVector(), CamCalibration::m_CH, CamCalibration::Mat3x4Mul(), parameterNumber, point, CamCalibration::s_optimal, twomat_gradian(), and CamCalibration::v_camera.
Member Data Documentation
double ProjObs::target[2]
Definition at line 1581 of file CamCalibration.cpp.
int ProjObs::cam
Definition at line 1582 of file CamCalibration.cpp.
int ProjObs::hom
Definition at line 1583 of file CamCalibration.cpp.
Referenced by eval_func().
int ProjObs::point
Definition at line 1584 of file CamCalibration.cpp.
Referenced by eval_func().
int ProjObs::parameterNumber = 0 [static]
Definition at line 1585 of file CamCalibration.cpp.
Referenced by eval_func().
The documentation for this struct was generated from the following file:
/home/julian/devel/artvertiser/garfeild/calib/CamCalibration.cpp