bazar: Mat3x4 Struct Reference
Mat3x4 Struct Reference
#include <matvec.h>
Public Member Functions
void set (CvMat *m)
void setIdentity ()
void setMul (const Mat3x3 &a, const Mat3x4 &b)
void setMul (const Mat3x4 &a, const Mat3x4 &b)
void mul (const Mat3x4 &a)
void setInverseByTranspose (const Mat3x4 &m)
void setRotate (const Vec3 &axis, double angle)
void setTranslate (double x, double y, double z)
void transform (const float src[4], float dst[4])
double det ()
Public Attributes
double m [3][4]
Detailed Description
Examples:
multigl.cpp.
Definition at line 59 of file matvec.h.
Member Function Documentation
void Mat3x4::set (CvMat * m)
Definition at line 20 of file matvec.cpp.
References m, and setIdentity().
void Mat3x4::setIdentity ()
Definition at line 14 of file matvec.cpp.
References m.
Referenced by PerspectiveCamera::clearExternalParams(), set(), and setTranslate().
void Mat3x4::setMul (const Mat3x3 & a, const Mat3x4 & b)
Definition at line 40 of file matvec.cpp.
References Mat3x3::m, and m.
Referenced by PerspectiveCamera::cmpWorldToImageMat(), and mul().
void Mat3x4::setMul (const Mat3x4 & a, const Mat3x4 & b)
Add a line [0, 0, 0, 1] to each matrix to fake 4x4 matrix multiplication.
Definition at line 82 of file matvec.cpp.
References m.
void Mat3x4::mul (const Mat3x4 & a)
Examples:
multigl.cpp.
Definition at line 97 of file matvec.cpp.
References setMul().
Referenced by photo_draw().
void Mat3x4::setInverseByTranspose (const Mat3x4 & m)
Examples:
multigl.cpp.
Definition at line 112 of file matvec.cpp.
References m.
Referenced by PerspectiveCamera::cmpWorldToImageMat(), PerspectiveCamera::loadTdir(), and photo_draw().
void Mat3x4::setRotate (const Vec3 & axis, double angle)
Examples:
multigl.cpp.
Definition at line 132 of file matvec.cpp.
References m.
Referenced by photo_draw().
void Mat3x4::setTranslate (double x, double y, double z)
Examples:
multigl.cpp.
Definition at line 104 of file matvec.cpp.
References m, and setIdentity().
Referenced by photo_draw().
void Mat3x4::transform (const float src[4], float dst[4])
Examples:
multigl.cpp.
Definition at line 52 of file matvec.cpp.
References m.
Referenced by photo_draw().
double Mat3x4::det () [inline]
Definition at line 71 of file matvec.h.
References m.
Referenced by PerspectiveCamera::loadTdir().
Member Data Documentation
double Mat3x4::m[3][4]
Examples:
multigl.cpp.
Definition at line 60 of file matvec.h.
Referenced by det(), PerspectiveCamera::loadTdir(), operator<<(), photo_draw(), PerspectiveCamera::saveTdir(), set(), PerspectiveCamera::setByTarget(), PerspectiveCamera::setGlModelView(), setIdentity(), setInverseByTranspose(), setMul(), Vec3::setMul(), setRotate(), setTranslate(), transform(), and PerspectiveCamera::translate().
The documentation for this struct was generated from the following files:
/home/julian/devel/artvertiser/garfeild/calib/matvec.h
/home/julian/devel/artvertiser/garfeild/calib/matvec.cpp