bazar: PoseObs Struct Reference
PoseObs Struct Reference
Public Member Functions
PoseObs ()
virtual int get_nb_measures () const
virtual void eval_func (const double *params, double *f, double *J, void **user_data) const
Public Attributes
double target [2]
int cam
int point
Detailed Description
Definition at line 371 of file CamAugmentation.cpp.
Constructor & Destructor Documentation
PoseObs::PoseObs () [inline]
Definition at line 376 of file CamAugmentation.cpp.
Member Function Documentation
virtual int PoseObs::get_nb_measures () const [inline, virtual]
Implements ls_minimizer2::observation.
Definition at line 379 of file CamAugmentation.cpp.
void PoseObs::eval_func (const double * params, double * f, double * J, void ** user_data) const [virtual]
Implements ls_minimizer2::observation.
Definition at line 384 of file CamAugmentation.cpp.
References cvmGet(), CamCalibration::ExtractRotationTranslationFrom3x4Matrix(), CamCalibration::HomogenousNormalizeVector(), CamCalibration::Mat3x4Mul(), point, CamAugmentation::s_optimal, twomat_gradian(), CamAugmentation::v_homography, CamAugmentation::v_homography_r_t, and CamAugmentation::v_homography_r_t_jacobian.
Member Data Documentation
double PoseObs::target[2]
Definition at line 373 of file CamAugmentation.cpp.
int PoseObs::cam
Definition at line 374 of file CamAugmentation.cpp.
int PoseObs::point
Definition at line 375 of file CamAugmentation.cpp.
Referenced by eval_func().
The documentation for this struct was generated from the following file:
/home/julian/devel/artvertiser/garfeild/calib/CamAugmentation.cpp